### ISSUE TITLE
centos7.4 ---> rhel7.4

### ISSUE THREAD

**Issue by zhentianzhang** [oamg/convert2rhel#1033]
centos7.4 ---> rhel7.4     
So how do we do this？

**Comment by bocekm** [comment]
Hi @zhentianzhang. Convert2rhel is not designed for landing on an unmaintained/end of life versions of RHEL. The tool requires you to update to CentOS Linux 7.9 first and then convert to RHEL 7.9 as described in https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/converting_from_an_rpm-based_linux_distribution_to_rhel/index.

**Comment by zhentianzhang** [comment]
> 嗨 。Convert2rhel 不是为登陆未维护/生命周期结束的 RHEL 版本而设计的。该工具要求您先更新到 CentOS Linux 7.9，然后再转换为 RHEL 7.9，如 https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/converting_from_an_rpm-based_linux_distribution_to_rhel/index 中所述。

What if I didn't update my system to version 7.9?

**Comment by bocekm** [comment]
You can still do so. It's a necessary pre-requisite for a successful conversion to RHEL 7. Running `yum update -y` should get your system updated from CentOS Linux 7.4 to 7.9.
