### ISSUE TITLE
Disabling repositories fails if there are no repositories available through subscriptions

### ISSUE THREAD

**Issue by neutralalice** [oamg/convert2rhel#1034]
From Centos 7 ( 3.10.0-1160.105.1.el7.x86_64 ) to rhel 7

Seems to fail if there is no subscription repositories being used on the host to be converted. Unsure if this is intended to fail here or if the case for there being no repositories is not defined.

relevant files?
https://github.com/oamg/convert2rhel/blob/c24bdb60ebceec84118936d1bbd532fbce42802d/convert2rhel/subscription.py#L657
https://github.com/oamg/convert2rhel/blob/main/convert2rhel/toolopts.py

```
[2024-01-17T12:05:08+0000] TASK - [Convert: Subscription Manager - Disable all repositories] *********
CRITICAL - Could not disable subscription-manager repositories:
This system has no repositories available through subscriptions.

ERROR - (ERROR) SUBSCRIBE_SYSTEM::FAILED_TO_DISABLE_SUBSCRIPTION_MANAGER_REPOSITORIES - Could not disable repositories through subscription-manager.
 Description: As part of the conversion process, convert2rhel disables all current subscription-manager repositories and enables only repositories required for the conversion. convert2rhel was unable to disable these repositories, and the conversion is unable to proceed.
 Diagnosis: Failed to disable repositories: This system has no repositories available through subscriptions.
.
 Remediation: N/A

ERROR - Skipped ENSURE_KERNEL_MODULES_COMPATIBILITY. Skipped because SUBSCRIBE_SYSTEM was not successful
ERROR - Skipped VALIDATE_PACKAGE_MANAGER_TRANSACTION. Skipped because ENSURE_KERNEL_MODULES_COMPATIBILITY and SUBSCRIBE_SYSTEM were not successful
```

**Comment by bocekm** [comment]
This might be related to https://issues.redhat.com/browse/RHELC-697.

@neutralalice, I suppose you've passed Red Hat account credentials to convert2rhel, either through /etc/convert2rhel.ini or through command line options.

Does the Red Hat account have at least one subscription available? You can veridy that under https://access.redhat.com/management/subscriptions.
And does your account have Simple Content Access enabled https://access.redhat.com/articles/simple-content-access? We recommend having that enabled.

**Comment by neutralalice** [comment]
Yes, I passed in an activation key and org through the ini. I don't have access to check that page apparently but I bet I know what has happened now thanks to your response. Our licensing folk seem to have neglected to enable rhel7 repositories(but they enabled rhel 8 and rhel 9 baseos/appstream; likely an oversight since all of our machines are doing the centos7->rhel7->8->9 migration.

![image](https://github.com/oamg/convert2rhel/assets/53350098/8d7a4b28-f9cc-4432-b15f-e90bd8c6acd0)

I sent them an email to check if this is the case, but based off of what I can see it probably is.

**Comment by neutralalice** [comment]
Well, they gave me access to see that page and it looks like there 25+ subscriptions. It's not clear to me if SCA is enabled since I don't see any tickboxes, but I assume it's not because I get "System Purpose Status: Matched" on some of the VM's that are registered if I check the status.

**Comment by bocekm** [comment]
Regarding the SCA, you don't see this UI switch, is that so?
![Screenshot from 2024-01-18 20-06-21](https://github.com/oamg/convert2rhel/assets/9884110/529847bf-898c-4b9c-a9d8-800bec3ae7e7)

With SCA enabled you wouldn't need to worry about what subscriptions are tied to the activation key you've used.

Let's suppose you have SCA disabled. To see what subscriptions are associated to the activation key, go to https://access.redhat.com/management/activation_keys. With SCA disabled you need to have a RHEL subscription associated with the activation key.

**Comment by neutralalice** [comment]
That's correct - unable to see the tickbox there. I can see it on my personal non-corporate login, so this will probably just be a continual back and forth with the licensing folk at work to give me the right permissions to see things. Unable to also view the activation keys page.

I am making an assumption here, but I imagine I can try to find the information with subscription-manager. Since it's likely I'll be playing cat and mouse to get permissions

On a RHEL 9 registered VM using the same activation key
```
+-------------------------------------------+
   Consumed Subscriptions
+-------------------------------------------+
Subscription Name:   Red Hat Enterprise Linux for Virtual Datacenters, Standard
Provides:            Red Hat Beta
                     Red Hat Enterprise Linux Atomic Host
                     Red Hat CodeReady Linux Builder for x86_64
                     Red Hat Enterprise Linux Atomic Host Beta
                     Oracle Java (for RHEL Server)
                     Red Hat Developer Tools (for RHEL Server)
                     Red Hat Developer Tools Beta (for RHEL Server)
                     Red Hat Developer Toolset (for RHEL Server)
                     Red Hat Software Collections (for RHEL Server)
                     Red Hat Enterprise Linux for x86_64
                     Red Hat Software Collections Beta (for RHEL Server)
                     dotNET on RHEL (for RHEL Server)
                     Red Hat Ansible Engine
                     Red Hat Enterprise Linux Server
...
Subscription Type:   Standard

```

On the Centos7 machine to be migrated using the same key as above
```
[root@migrationtest ~]# sudo subscription-manager list --consumed
You are attempting to use a locale that is not installed.
No consumed subscription pools were found.


[root@migrationtest ~]# sudo subscription-manager status
You are attempting to use a locale that is not installed.
+-------------------------------------------+
   System Status Details
+-------------------------------------------+
Overall Status: Current

System Purpose Status: Mismatched
- The service level preference "Standard" is not provided by a currently consumed subscription.
```

**Comment by neutralalice** [comment]
I've now got SCA enabled from the licensing folks, and the tool seems to be running - so agree with you that this is a subscription association issue. 

I do still think that the wording is a bit nebulous and doesn't really characterize what the issue can boil down to. But I suppose that could be clarified by possible remediations being listed.
