### ISSUE TITLE
Convert2rhel failed to convert Rocky 8.9 to rhel 8.9 on Satellete server

### ISSUE THREAD

**Issue by flaks-cshl** [oamg/convert2rhel#1166]
Got this error: 
Errors during downloading metadata for repository 'rhel-8-for-x86_64-baseos-rpms':
 - Status code: 404 for https://satellite.NNNN.NNN/pulp/content/CSHL/Batch_1/RHEL_8_Standard/content/dist/rhel8/8.9/x86_64/baseos/os/repodata/repomd.xml
 -  Error: Failed to download metadata for repo 'rhel-8-for-x86_64-baseos-rpms': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
 
There is nothing at this URL I can see this repomd.xml file under different path: 
https://satellite.NNNN.NNN/pulp/content/CSHL/Batch_1/RHEL_8_Standard/content/dist/rhel8/8.9/x86_64/baseos/kickstart/repodata/repomd.xml
'os' in the path is replaced with 'kickstart'. Sateelite is fully operational.

**Comment by bocekm** [comment]
@flaks-cshl, one thing that comes to my mind is that you perhaps synced to the Satellite server the _Red Hat Enterprise Linux 8 for x86_64 - BaseOS RPMs **8**_ repo and not the _Red Hat Enterprise Linux 8 for x86_64 - BaseOS RPMs **8.9**_ repo. There's a subtle but important difference. The RHEL **8** means 8.latest which is as of now **8.9** however when syncing repos to Satellite, the RHEL 8 repo is stored under a different URL than the RHEL 8.9 repo. And convert2rhel expects the repo to be under the URL for 8.9, not just 8.

@bookwar, I've seen the kind of a Satellite setup "mistake" I describe above a couple of times. For a user this must sound like something the tool should be able to take of and accept both Satellite setups. When the system to be converted is of version 8.9, we pass the same minor release version to all conversion yum calls (`--releasever=8.9`) based on this simple mapping https://github.com/oamg/convert2rhel/blob/main/convert2rhel/systeminfo.py#L41. We can introduce a fallback to releasever `8` if the repo for `8.9` is not accessible.

I can see that our [docs](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/converting_from_an_rpm-based_linux_distribution_to_rhel/index#proc_preparing-for-a-rhel-conversion_converting-using-the-command-line) talk about syncing only RHEL 8.8 or 8.6 repos but 8.9 should be listed there as well. I've make sure the 8.9 is added there.

**Comment by flaks-cshl** [comment]
@bocekm, Thank you for a quick reply. 
If I look at available repos on Satellite, I can only see RHEL 8 repos. There is no 8.9 repos except for Kickstart RPM's. However, there is no path for 8 in URL - only for 8.9, if I browse web interface.
Strangely enough if I look at /etc/yum.repos.d/redhat.repo file on the system that was provisioned in Satellite, I see this stanza:
`[rhel-8-for-x86_64-baseos-rpms]
name = Red Hat Enterprise Linux 8 for x86_64 - BaseOS (RPMs)
baseurl = https://satellite.NNNN.NNN/pulp/content/CSHL/Batch_1/RHEL_8_Standard/content/dist/rhel8/$releasever/x86_64/baseos/os`
which also has 'os' at the end. I can replace $releaseveer with 8.9 and there is only kickstart directory in the path 'os' does not exist. System is somehow happily getting updates. I have no idea how did kicktart got into the path but it seems to be the  problem for conver2html program but not for dnf. 
RHEL 9 has identical structure and dnf and provisioning also work as expected.

**Comment by bocekm** [comment]
I don't have that broad of a Satellite knowledge. Try going to [https://<sat_hostname>/redhat_repositories]() and try enabling RHEL 8.9 BaseOS and AppStream repos following the screenshot below. If you don't see it there, you may want to open a customer case with Red Hat at https://access.redhat.com/support/cases/.
![Screenshot from 2024-04-03 22-12-12](https://github.com/oamg/convert2rhel/assets/9884110/55bd7da9-a74b-462e-bbf2-9e5a029c1810)

**Comment by lflaks** [comment]
I found 8.9 repositories, added them and ran the sync job. Unfortunately, the error i had is still there. Looks like the problem is on the satellite side. I will contact RedHat on that.
Thanks!

**Comment by flaks-cshl** [comment]
As it turned out, I had to add 8.9 repos to the corresponding Lifecycle Environment and Content View. That solved my problem.
Thank you @bocekm - you directed me into the right path!
