### ISSUE TITLE
Passing environment variables

### ISSUE THREAD

**Issue by markm-ocp** [oamg/convert2rhel#1185]
What is the header for passing environmental variables in the config file?

**Comment by r0x0d** [comment]
Hi, @markm-ocp!  Thanks for your question. 

Currently, we don't have a way of passing environment variables through the config file right now. 

If you want to follow the development of this item, the work is being tracked under here: https://issues.redhat.com/browse/RHELC-1496.

**Comment by markm-ocp** [comment]
thank you! @r0x0d - I ended up doing the following:

`echo convert2rhel`
`export CONVERT2RHEL_DISABLE_TELEMETRY=1, CONVERT2RHEL_ALLOW_UNAVAILABLE_KMODS=1, CONVERT2RHEL_UNSUPPORTED_INCOMPLETE_ROLLBACK=1, CONVERT2RHEL_SKIP_KERNEL_CURRENCY_CHECK=1, CONVERT2RHEL_TAINTED_KERNEL_MODULE_CHECK_SKIP=1`
`convert2rhel --no-rpm-va`
