### ISSUE TITLE
Error during unpacking rpm package filesystem-2.4.30-3.el6.x86_64 when converting from CENTOS6 to RHEL6

### ISSUE THREAD

**Issue by ahilden** [oamg/convert2rhel#123]
I am getting the following errors when running convert2rhel on all CENTOS6 systems.  Although it does look the package is installed.  This causes the convert2rhel script to fail. After it fails what are the possible recovery paths to complete the conversion?

Resolving Dependencies
--> Running transaction check
---> Package filesystem.x86_64 0:2.4.30-3.el6 will be reinstalled
--> Finished Dependency Resolution
Dependencies Resolved
================================================================================
 Package         Arch        Version              Repository               Size
================================================================================
Reinstalling:
 filesystem      x86_64      2.4.30-3.el6         rhel-6-server-rpms      1.0 M
Transaction Summary
================================================================================
Reinstall     1 Package(s)
Total download size: 1.0 M
Installed size: 0  
Downloading Packages:
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
  Installing : filesystem-2.4.30-3.el6.x86_64                               1/1Error unpacking rpm package filesystem-2.4.30-3.el6.x86_64
error: unpacking of archive failed on file /sys: cpio: chown
  Verifying  : filesystem-2.4.30-3.el6.x86_64                               1/1 
Failed:
  filesystem.x86_64 0:2.4.30-3.el6                                              
Complete!
Received return code: 1
Resolving dependency errors ... 
Found protected packages: []
Found deps packages: []
Found multilib packages: []
Found req packages: []
No other package to try to downgrade in order to resolve yum dependency errors.
[11/19/2020 16:50:51] CRITICAL - Could not resolve yum errors.

**Comment by SpyTec** [comment]
Hi!

Are you able to get the machine working by rebooting and running `yum update -y` after the error has occurred? Does this happen on version 0.13 or an older version? `yum list convert2rhel`

**Comment by bocekm** [comment]
Hi, thanks for the report.

Please make sure that your `/` and `/sys/` folders are not mounted as read-only (https://unix.stackexchange.com/questions/173896/sys-cpio-chown-failed-read-only-file-system-building-passenger-rpm-using-d).

Regarding the possible recovery - the failure happened after the point where conver2rhel is able to do a rollback.
But you can try going to `/var/lib/convert2rhel/` and run `rpm -i --replacepkgs *rpm`. That should at least get you to a point from where you can run convert2rhel again.

**Comment by ahilden** [comment]
The version of convert2rhel I have installed was  `0.9-1.el6`.  I was able to revert.  The backup of the rpms was in `/tmp/convert2rhel` as opposed to `/var/lib/convert2rhel`.  I was able to run `rpm -i --replacepkgs *rpm` and will be trying to move forward again.  I'm not sure what is wrong with sys, although it seems like all of our centos6 system are like this though and they indirectly cause the filesystem package to fail to install.  

```
[root@dashdb-prod-staging-txn-test2 ahilden]# mount |grep sys
sysfs on /sys type sysfs (rw)
none on /proc/sys/fs/binfmt_misc type binfmt_misc (rw)
[root@dashdb-prod-staging-txn-test2 ahilden]# chown root /sys
chown: changing ownership of `/sys': Read-only file system
[root@dashdb-prod-staging-txn-test2 ahilden]# 
```

Investigating....

**Comment by bocekm** [comment]
We'll be adding checks for /sys/ being mounted as rw to convert2rhel. It's tracked internally under https://issues.redhat.com/browse/OAMG-4310.
Before that happens, we'll have a warning in the main article https://access.redhat.com/articles/2360841 soon.
Thanks for your time spent on this issue, @ahilden.
