### ISSUE TITLE
Error getting repository data for rhel-7-server-optional-rpms, repository not found

### ISSUE THREAD

**Issue by Turivniy** [oamg/convert2rhel#13]
Trying to play with convert2rhel. 
Got an error on a Centos 7 vm
`Linux localhost.localdomain 3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Preconditions:**
* Centos: http://isoredirect.centos.org/centos/7/isos/x86_64/

**Steps to reproduce:**

- `# yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm`
- `# yum install -y convert2rhel`
- `# yum update -y`
- `# reboot`
- `# convert2rhel --disable-submgr --disablerepo "*" --enablerepo rhel-7-server-optional-rpms --debug`

**Actual result:**
Got an error:
```[02/07/2020 09:15:31] DEBUG - Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/convert2rhel/main.py", line 76, in main
    pre_ponr_conversion()
  File "/usr/lib/python2.7/site-packages/convert2rhel/main.py", line 167, in pre_ponr_conversion
    repo.check_needed_repos_availability(repos_needed)
  File "/usr/lib/python2.7/site-packages/convert2rhel/repo.py", line 255, in check_needed_repos_availability
    avail_repos = get_avail_repos()
  File "/usr/lib/python2.7/site-packages/convert2rhel/repo.py", line 282, in get_avail_repos
    loggerinst.critical("yum repolist command failed: \n\n" + repos_raw)
  File "/usr/lib/python2.7/site-packages/convert2rhel/logger.py", line 100, in critical
    sys.exit(1)
SystemExit: 1
```
Full trace:
http://pastebin.test.redhat.com/834166

**Expected result:**
The script was executed without any errors

**Comment by Turivniy** [comment]
Trying with repos: `rhel-7-server-optional-rpms` and `rhel-7-server-optional-rpms`

**Comment by bocekm** [comment]
From the official docs at https://access.redhat.com/articles/2360841:
> Ensure that you have an access to RHEL packages through custom repositories configured in the /etc/yum.repos.d/ directory and pointing, for example, to RHEL ISO, FTP, or HTTP. Note that the OS will be converted to the version of RHEL provided by these repositories. See instructions on how to configure a repository.

> `# convert2rhel --disable-submgr --disablerepo "*" --enablerepo <RHEL_RepoID> --debug`
Replace RepoID with your custom repository configured in the /etc/yum.repos.d/ directory, for example, rhel-7-server-rpms.

Anyway, it doesn't matter if the repoid is  `rhel-7-server-rpms`, `rhel-7-server-optional-rpms` or `my_rhel7_repo`, the requirement is that the repoid you use in the `--enablerepo` option is defined in /etc/yum.repos.d/*.repo. It seems that in your case it is not, as implied by the message: `Error getting repository data for rhel-7-server-optional-rpms, repository not found`.

**Comment by Turivniy** [comment]
Thanks, @bocekm I'll try to follow the official docs.
