### ISSUE TITLE
Post Conversion Action Framework merge order

### ISSUE THREAD

**Issue by pr-watson** [oamg/convert2rhel#1331]
Merge Order:

- [x] Port function::pkgmanager.create_transaction_handler() https://github.com/oamg/convert2rhel/pull/1152
- [x] Port function::pkghandler.preserve_only_rhel_kernel()  https://github.com/oamg/convert2rhel/pull/1250
- [x] Port function::pkghandler.list_non_red_hat_pkgs_left() https://github.com/oamg/convert2rhel/pull/1292
- [x] Port function::grub.post_ponr_set_efi_configuration() https://github.com/oamg/convert2rhel/pull/1256
- [x] Port function::redhatrelease.PkgManagerConf().patch() https://github.com/oamg/convert2rhel/pull/1321
- [x] Port function::subscription.lock_releasever_in_rhel_repositories() https://github.com/oamg/convert2rhel/pull/1326
- [x] Port function::systeminfo.modified_rpm_files_diff() https://github.com/oamg/convert2rhel/pull/1266
- [x] Port function::grub.update_grub_after_conversion() https://github.com/oamg/convert2rhel/pull/1303
- [x] Port function::utils.remove_tmp_dir()  https://github.com/oamg/convert2rhel/pull/1283
- [x] Port function::checks.check_kernel_boot_files() https://github.com/oamg/convert2rhel/pull/1301
- [x] Port function: hostmetering.configure_host_metering() https://github.com/oamg/convert2rhel/pull/1311
- [ ] Port function::subscription.update_rhsm_custom_facts() https://github.com/oamg/convert2rhel/pull/1299
- [x] Port function::breadcrumbs.finish_collection() https://github.com/oamg/convert2rhel/pull/1305

**Comment by r0x0d** [comment]
added https://github.com/oamg/convert2rhel/pull/1292 to the list as it was missing

**Comment by bookwar** [comment]
Merge-if-tests-are-ok checklist:

- [ ] Port function::grub.post_ponr_set_efi_configuration()
      https://github.com/oamg/convert2rhel/pull/1256
- [ ] Port function::redhatrelease.PkgManagerConf().patch()
      https://github.com/oamg/convert2rhel/pull/1321
- [ ] Port function::subscription.lock_releasever_in_rhel_repositories()
      https://github.com/oamg/convert2rhel/pull/1326
- [ ] Port function::systeminfo.modified_rpm_files_diff()
      https://github.com/oamg/convert2rhel/pull/1266
- [ ] Port function::grub.update_grub_after_conversion()
      https://github.com/oamg/convert2rhel/pull/1303
- [ ] Port function::utils.remove_tmp_dir()
      https://github.com/oamg/convert2rhel/pull/1283
- [ ] Port function::checks.check_kernel_boot_files()
      https://github.com/oamg/convert2rhel/pull/1301
- [ ] Port function::subscription.update_rhsm_custom_facts()
      https://github.com/oamg/convert2rhel/pull/1299
- [ ] Port function::breadcrumbs.finish_collection()
      https://github.com/oamg/convert2rhel/pull/1305
- [ ] Port function: hostmetering.configure_host_metering()
      https://github.com/oamg/convert2rhel/pull/1311
