### ISSUE TITLE
Error: Unknown repo: 'rhel-8-baseos'

### ISSUE THREAD

**Issue by HartmutManz** [oamg/convert2rhel#160]

**Comment by bocekm** [comment]
Hi Harmut.

You need to have the rhel-8-baseos repository defined in /etc/yum.repos.d/. But BaseOS repo is not enough to convert CentOS/OL 8 to RHEL. You need the AppStream repo as well.

Related quotes from [the documentation](https://access.redhat.com/articles/2360841):
> Ensure that you have an access to RHEL packages through custom repositories configured in the /etc/yum.repos.d/ directory and pointing, for example, to [RHEL ISO](https://access.redhat.com/downloads/content/69/), FTP, or HTTP. Note that the OS will be converted to the version of RHEL provided by these repositories. Make sure that the RHEL minor version is the same or later than the original OS minor version to prevent downgrading and potential conversion failures. See [instructions on how to configure a repository](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/system_administrators_guide/ch-yum#sec-Setting_repository_Options).

> RHEL 8 content is distributed through two default repositories, BaseOS and AppStream. You must configure both for a successful conversion. When running the Convert2RHEL utility, make sure to enable both repositories using the --enablerepo option. For more information, see [Considerations in adopting RHEL 8](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/considerations_in_adopting_rhel_8/index#repositories_considerations-in-adopting-RHEL-8).

Let me know if that helps.

**Comment by bocekm** [comment]
Harmut, with the recently released version 0.16, you can now convert the system much easier without the need to configure the above repositories manually. Read the updated article https://access.redhat.com/articles/2360841 on how to use convert2rhel with Red Hat Subscription Manager (RHSM).
