### ISSUE TITLE
error when executing convert2rhel via an Ansible playbook

### ISSUE THREAD

**Issue by r4han85** [oamg/convert2rhel#161]
Hello, 
I work about an automotion way to convert 80/100 servers to rhel8 with a playbook.

When I execute convert2rhel locally with this command, it's ok:
` convert2rhel --disable-submgr --disablerepo="*" --enablerepo=rhel-BaseOS --enablerepo=rhel-AppStream -v Server -y `

But, when I execute this inside the playbook, convertion failed, and log this in /var/log/convert2rhel/convert2rhel.log :
`
01/28/2021 15:18:12] TASK - [Prepare: End user license agreement] ******************************
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/convert2rhel/main.py", line 61, in main
    user_to_accept_eula()
  File "/usr/lib/python3.6/site-packages/convert2rhel/main.py", line 137, in user_to_accept_eula
    eula_text = utils.get_file_content(eula_filepath)
  File "/usr/lib/python3.6/site-packages/convert2rhel/utils.py", line 82, in get_file_content
    lines = file_to_read.readlines()
  File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 318: ordinal not in range(128)

No changes were made to the system. `

I try to force locale to en_US.UTF8 before convertion task, but it still fails.

Do you have a tip to succeed ?

**Comment by r4han85** [comment]
Problem solved,
I've added environment variable to the task 
 environment:
  LANG: en_US.UTF8
and it works !

**Comment by bocekm** [comment]
Thanks for the report. For the record, what was the locale that was causing this failure? I can try to reproduce it and possibly find a solution so it does not exit the hard way.

**Comment by r4han85** [comment]
Our servers are supposed to be set up with it. While looking for the cause
of this error, I went through the python scripts in the package, and found
that the EULA file did indeed contain non-ASCII characters, which I think
is causing the error I encountered.

Étienne Mollet

Le jeu. 28 janv. 2021 à 20:22, Michal Bocek <notifications@github.com> a
écrit :

**Comment by bocekm** [comment]
That's OK, our EULA indeed contained non-ASCII chars. Fix in https://github.com/oamg/convert2rhel/pull/162/.
We actually had an oudated EULA so thanks for making me look at it :)
I'll test if the fr_FR.UTF8 does not cause problems later in the tool execution.

**Comment by r4han85** [comment]
glad to see that you had already solved this issue,

when the next version is available i will download it and use it to do most
of the conversions.

thanks for your work and time,


Étienne Mollet

Le jeu. 28 janv. 2021 à 21:29, Michal Bocek <notifications@github.com> a
écrit :

**Comment by bocekm** [comment]
I've tried the conversion with the latest version 0.16 and with the french locale and it seems to work fine now.
