### ISSUE TITLE
There is still CentOS screen when booting after CentOS6.9 consersion.

### ISSUE THREAD

**Issue by zhangfanook2** [oamg/convert2rhel#164]
Please check attachment. Thanks. 
[log.tar.gz](https://github.com/oamg/convert2rhel/files/5897406/log.tar.gz)

**Comment by bocekm** [comment]
Hi Fan, thanks for filing the bug report.
Do you mean the grub kernel selection (grub splash screen) is CentOS-themed or the graphical screen shown when already loading the system (plymouth) is CentOS-themed?
Files for both of these are stored in the `redhat-logos` package and based on the log this package was replaced by the RHEL version of the package. I suspect we need to execute either some grub or plymouth command to activate the RHEL theme.

**Comment by zhangfanook2** [comment]
> Files for both of these are stored in the `redhat-logos` package and based on the log you've attached this package was replaced by the RHEL version of the package. I suspect we need to execute either some grub or plymouth command to activate the RHEL theme.

**Comment by zhangfanook2** [comment]
> Hi Fan, thanks for filing the bug report.
> Is it the grub kernel selection (grub splash screen) that is CentOS-themed or the graphical screen shown when already loading the system (plymouth)?
> Files for both of these are stored in the `redhat-logos` package and based on the log you've attached this package was replaced by the RHEL version of the package. I suspect we need to execute either some grub or plymouth command to activate the RHEL theme.

Hi, Michal

There sould be plymouth, please check picture as below. 
![傲游浏览器截图20210128201751](https://user-images.githubusercontent.com/69416968/106706732-13fe6c80-662b-11eb-9a26-6f2914b7daf3.jpg)

**Comment by bocekm** [comment]
Closing this one as Red Hat doesn't officially support CentOS Linux 6 conversions anymore. The reason is that RHEL 6 is in a very limited Extended life cycle support (ELS) since 2020.
