### ISSUE TITLE
Error: CentOS 8.2 conversion failed

### ISSUE THREAD

**Issue by zhangfanook2** [oamg/convert2rhel#165]
**1. mound RHEL8.2 ISO to /cdrom
2. Create local AppStream and BaseOS repo files as below:**

myAppStream.repo
[LocalRepo_AppStream]
name=LocalRepository_AppStream
baseurl=file:///cdrom/AppStream
enabled=1
gpgcheck=0
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release

myBaseOS.repo
[LocalRepo_BaseOS]
name=LocalRepository_BaseOS
baseurl=file:///cdrom/BaseOS
enabled=1
gpgcheck=0
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release

3. yum updat and reboot
4. convert2rhel --disable-submgr --enablerepo LocalRepo_BaseOS --enablerepo LocalRepo_AppStream --debug
5. but failed, the logs in attachment.

`Error: 
 Problem 1: package mesa-libxatracker-19.3.4-2.el8.x86_64 requires libLLVM-9.so()(64bit), but none of the providers can be installed
  - package mesa-libxatracker-19.3.4-2.el8.x86_64 requires libLLVM-9.so(LLVM_9)(64bit), but none of the providers can be installed
  - cannot install the best update candidate for package mesa-libxatracker-20.1.4-1.el8.x86_64
  - package llvm-libs-9.0.1-4.module+el8.2.0+5887+847e8a86.x86_64 is filtered out by modular filtering
 Problem 2: package mesa-dri-drivers-19.3.4-2.el8.x86_64 requires libLLVM-9.so()(64bit), but none of the providers can be installed
  - package mesa-dri-drivers-19.3.4-2.el8.x86_64 requires libLLVM-9.so(LLVM_9)(64bit), but none of the providers can be installed
  - cannot install the best update candidate for package mesa-dri-drivers-20.1.4-1.el8.x86_64
  - package llvm-libs-9.0.1-4.module+el8.2.0+5887+847e8a86.x86_64 is filtered out by modular filtering
 Problem 3: package crypto-policies-scripts-20200713-1.git51d1222.el8.noarch requires crypto-policies = 20200713-1.git51d1222.el8, but none of the providers can be installed
  - crypto-policies-20200713-1.git51d1222.el8.noarch does not belong to a distupgrade repository
  - problem with installed package crypto-policies-scripts-20200713-1.git51d1222.el8.noarch
 Problem 4: package pipewire0.2-libs-0.2.7-6.el8.x86_64 conflicts with pipewire-libs(x86-64) <= 0.2.7 provided by pipewire-libs-0.2.7-1.el8.x86_64
  - cannot install the best update candidate for package pipewire-libs-0.3.6-1.el8.x86_64
  - problem with installed package pipewire0.2-libs-0.2.7-6.el8.x86_64
 Problem 5: package qemu-kvm-15:4.2.0-34.module_el8.3.0+613+9ec9f184.1.x86_64 requires mesa-dri-drivers, but none of the providers can be installed
  - package mesa-dri-drivers-19.3.4-2.el8.i686 requires libLLVM-9.so, but none of the providers can be installed
  - package mesa-dri-drivers-19.3.4-2.el8.i686 requires libLLVM-9.so(LLVM_9), but none of the providers can be installed
  - package mesa-dri-drivers-19.3.4-2.el8.x86_64 requires libLLVM-9.so()(64bit), but none of the providers can be installed
  - package mesa-dri-drivers-19.3.4-2.el8.x86_64 requires libLLVM-9.so(LLVM_9)(64bit), but none of the providers can be installed
  - mesa-dri-drivers-20.1.4-1.el8.x86_64 does not belong to a distupgrade repository
  - problem with installed package qemu-kvm-15:4.2.0-34.module_el8.3.0+613+9ec9f184.1.x86_64
  - package llvm-libs-9.0.1-4.module+el8.2.0+5887+847e8a86.i686 is filtered out by modular filtering
  - package llvm-libs-9.0.1-4.module+el8.2.0+5887+847e8a86.x86_64 is filtered out by modular filtering
 Problem 6: problem with installed package mesa-libxatracker-20.1.4-1.el8.x86_64
  - package mesa-libxatracker-19.3.4-2.el8.x86_64 requires libLLVM-9.so()(64bit), but none of the providers can be installed
  - package mesa-libxatracker-19.3.4-2.el8.x86_64 requires libLLVM-9.so(LLVM_9)(64bit), but none of the providers can be installed
  - mesa-libxatracker-20.1.4-1.el8.x86_64 does not belong to a distupgrade repository
  - package llvm-libs-9.0.1-4.module+el8.2.0+5887+847e8a86.x86_64 is filtered out by modular filtering
 Problem 7: package tigervnc-server-minimal-1.9.0-13.el8.x86_64 requires mesa-dri-drivers, but none of the providers can be installed
  - package mesa-dri-drivers-20.1.4-1.el8.x86_64 requires mesa-filesystem(x86-64) = 20.1.4-1.el8, but none of the providers can be installed
  - package mesa-dri-drivers-19.3.4-2.el8.i686 requires libLLVM-9.so, but none of the providers can be installed
  - package mesa-dri-drivers-19.3.4-2.el8.i686 requires libLLVM-9.so(LLVM_9), but none of the providers can be installed
  - package mesa-dri-drivers-19.3.4-2.el8.x86_64 requires libLLVM-9.so()(64bit), but none of the providers can be installed
  - package mesa-dri-drivers-19.3.4-2.el8.x86_64 requires libLLVM-9.so(LLVM_9)(64bit), but none of the providers can be installed
  - cannot install the best update candidate for package tigervnc-server-minimal-1.10.1-9.el8_3.x86_64
  - mesa-filesystem-20.1.4-1.el8.x86_64 does not belong to a distupgrade repository
  - package llvm-libs-9.0.1-4.module+el8.2.0+5887+847e8a86.i686 is filtered out by modular filtering
  - package llvm-libs-9.0.1-4.module+el8.2.0+5887+847e8a86.x86_64 is filtered out by modular filtering
 Problem 8: package mesa-dri-drivers-20.1.4-1.el8.x86_64 requires mesa-filesystem(x86-64) = 20.1.4-1.el8, but none of the providers can be installed
  - problem with installed package mesa-dri-drivers-20.1.4-1.el8.x86_64
  - cannot install both mesa-filesystem-19.3.4-2.el8.x86_64 and mesa-filesystem-20.1.4-1.el8.x86_64
  - package mesa-dri-drivers-19.3.4-2.el8.x86_64 requires libLLVM-9.so()(64bit), but none of the providers can be installed
  - package mesa-dri-drivers-19.3.4-2.el8.x86_64 requires libLLVM-9.so(LLVM_9)(64bit), but none of the providers can be installed
  - cannot install the best update candidate for package mesa-filesystem-20.1.4-1.el8.x86_64
  - package llvm-libs-9.0.1-4.module+el8.2.0+5887+847e8a86.x86_64 is filtered out by modular filtering
(try to add '--allowerasing' to command line to replace conflicting packages or '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
Received return code: 1

Resolving dependency errors ... 

Found protected packages: []
Found deps packages: []
Found multilib packages: []
Found req packages: []
No other package to try to downgrade in order to resolve yum dependency errors.
[01/30/2021 15:14:55] CRITICAL - Could not resolve yum errors.
[01/30/2021 15:14:55] DEBUG - Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/convert2rhel/main.py", line 89, in main
    post_ponr_conversion()
  File "/usr/lib/python3.6/site-packages/convert2rhel/main.py", line 192, in post_ponr_conversion
    pkghandler.replace_non_red_hat_packages()
  File "/usr/lib/python3.6/site-packages/convert2rhel/pkghandler.py", line 431, in replace_non_red_hat_packages
    call_yum_cmd_w_downgrades(cmd, system_info.fingerprints_orig_os)
  File "/usr/lib/python3.6/site-packages/convert2rhel/pkghandler.py", line 68, in call_yum_cmd_w_downgrades
    loggerinst.critical("Could not resolve yum errors.")
  File "/usr/lib/python3.6/site-packages/convert2rhel/logger.py", line 105, in critical
    sys.exit(msg)
SystemExit: Could not resolve yum errors.

WARNING - Conversion process interrupted and manual user intervention will be necessary.
[log.tar.gz](https://github.com/oamg/convert2rhel/files/5897533/log.tar.gz)
`

Could you please help a check? Thanks.

**Comment by bookwar** [comment]
We were not able to address the issue in time. CentOS 8 is now End of Life and the state of CentOS Stream 8 repositories has changed significantly.

Closing.

**Comment by bocekm** [comment]
I've installed all the problematic packages from this ticket description (mesa-libxatracker, mesa-dri-drivers, crypto-policies-scripts, pipewire0.2-libs, qemu-kvm, mesa-libxatracker, tigervnc-server-minimal) on the latest CentOS Linux 8.5 and it got converted to RHEL 8.5 just fine. We've improved the reliability of the transaction a lot (https://github.com/oamg/convert2rhel/pull/528) and it must have fixed this issue.
