### ISSUE TITLE
Fail when convert CentOS 7.9 to RHEL 7.9

### ISSUE THREAD

**Issue by jerry-wjl** [oamg/convert2rhel#166]
Hi Experts,
I installed a centos 7.9 server to test conver2rhel, the server is installed as "server with gui" and has totally 1348 pkgs installed. Below are some original info from the box.

[root@localhost ~]# cat /etc/centos-release
CentOS Linux release 7.9.2009 (Core)

[root@localhost ~]# uname  -r
3.10.0-1160.el7.x86_64

[root@localhost ~]# rpm -qa | wc -l
1348

[root@localhost ~]# yum repolist
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: mirrors.huaweicloud.com
 * extras: mirrors.ustc.edu.cn
 * updates: mirrors.ustc.edu.cn
repo id                                                                    repo name                                                                    status
base/7/x86_64                                                              CentOS-7 - Base                                                              10,072
extras/7/x86_64                                                            CentOS-7 - Extras                                                               448
updates/7/x86_64                                                           CentOS-7 - Updates                                                            1,216
repolist: 11,736

As the instruction, I use rhel 7.9 installation media to make a yum.

[root@localhost yum.repos.d]# cat > local.repo << EOF
> [rhel-7.9]
> name=rhel-7.9
> enabled=1
> gpgcheck=0
> baseurl=file:/media
> EOF

[root@localhost yum.repos.d]# ls
CentOS-Base.repo  CentOS-Debuginfo.repo  CentOS-Media.repo    CentOS-Vault.repo          local.repo
CentOS-CR.repo    CentOS-fasttrack.repo  CentOS-Sources.repo  CentOS-x86_64-kernel.repo

[root@localhost yum.repos.d]# yum repolist
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: mirrors.163.com
 * extras: mirrors.ustc.edu.cn
 * updates: mirrors.ustc.edu.cn
rhel-7.9                                                                                                                               | 2.8 kB  00:00:00
(1/2): rhel-7.9/group                                                                                                                  | 628 kB  00:00:00
(2/2): rhel-7.9/primary                                                                                                                | 2.1 MB  00:00:00
rhel-7.9                                                                                                                                            5230/5230
repo id                                                                    repo name                                                                    status
base/7/x86_64                                                              CentOS-7 - Base                                                              10,072
extras/7/x86_64                                                            CentOS-7 - Extras                                                               448
rhel-7.9                                                                   rhel-7.9                                                                      5,230
updates/7/x86_64                                                           CentOS-7 - Updates                                                            1,216
repolist: 16,966

Then I installed the convert2rhel tools and run the conversion:
[root@localhost ~]# yum install -y https://github.com/oamg/convert2rhel/releases/download/v0.15/convert2rhel-0.15-1.el7.noarch.rpm

[root@localhost ~]# convert2rhel --disable-submgr --enablerepo rhel-7.9 --debug

Then it will encounter an error in one of the step(replacing the centos kernel ), which complain a dependency error. The whole output is as below:

[01/31/2021 17:24:39] DEBUG - Calling command 'yum install -y --disablerepo=* --enablerepo=rhel-7.9 kernel'
Loaded plugins: fastestmirror, langpacks
Determining fastest mirrors
Package kernel-3.10.0-1160.el7.x86_64 already installed and latest version
Nothing to do

Conflict of kernels: One of the installed kernels has the same version as the latest RHEL kernel.
[01/31/2021 17:24:40] DEBUG - Calling command 'yum list -y --disablerepo=* --enablerepo=rhel-7.9 --showduplicates kernel'
WARNING - The convert2rhel is going to force-replace the only kernel installed, which has the same NEVRA as the only available RHEL kernel. If anything goes wrong with such replacement, the system will become unbootable. If you want the convert2rhel to install the RHEL kernel in a safer manner, you can install a different version of kernel first and then run convert2rhel again.

Continue with the system conversion? [y/n]: y

[01/31/2021 17:24:48] DEBUG - Downloading the kernel-3.10.0-1160.el7 package.
[01/31/2021 17:24:48] DEBUG - Calling command 'yumdownloader -v --disablerepo=* --enablerepo=rhel-7.9 --destdir="/var/lib/convert2rhel/" kernel-3.10.0-1160.el7'
Loading "fastestmirror" plugin
Loading "langpacks" plugin
Adding en_US.UTF-8 to language list
Config time: 0.006
Loading mirror speeds from cached hostfile
repo time: 0.001
Setting up Package Sacks
pkgsack time: 0.002
rpmdb time: 0.000
kernel-3.10.0-1160.el7.x86_64.rpm                                                                |  50 MB  00:00:00
Successfully downloaded the kernel-3.10.0-1160.el7 package.
[01/31/2021 17:24:48] DEBUG - Path of the downloaded package: /var/lib/convert2rhel/kernel-3.10.0-1160.el7.x86_64.rpm
Replacing CentOS Linux kernel-3.10.0-1160.el7 with RHEL kernel with the same NEVRA ...
[01/31/2021 17:24:48] DEBUG - Calling command 'rpm -i --force --replacepkgs /var/lib/convert2rhel/kernel-3.10.0-1160.el7*'
[01/31/2021 17:24:49] CRITICAL - Unable to replace kernel package: error: Failed dependencies:
        system-release is needed by kernel-3.10.0-1160.el7.x86_64

[01/31/2021 17:24:49] DEBUG - Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/convert2rhel/main.py", line 89, in main
    post_ponr_conversion()
  File "/usr/lib/python2.7/site-packages/convert2rhel/main.py", line 190, in post_ponr_conversion
    pkghandler.preserve_only_rhel_kernel()
  File "/usr/lib/python2.7/site-packages/convert2rhel/pkghandler.py", line 447, in preserve_only_rhel_kernel
    kernel_update_needed = install_rhel_kernel()
  File "/usr/lib/python2.7/site-packages/convert2rhel/pkghandler.py", line 487, in install_rhel_kernel
    handle_no_newer_rhel_kernel_available()
  File "/usr/lib/python2.7/site-packages/convert2rhel/pkghandler.py", line 509, in handle_no_newer_rhel_kernel_available
    replace_non_rhel_installed_kernel(installed[0])
  File "/usr/lib/python2.7/site-packages/convert2rhel/pkghandler.py", line 562, in replace_non_rhel_installed_kernel
    loggerinst.critical("Unable to replace kernel package: %s" % output)
  File "/usr/lib/python2.7/site-packages/convert2rhel/logger.py", line 105, in critical
    sys.exit(msg)
SystemExit: Unable to replace kernel package: error: Failed dependencies:
        system-release is needed by kernel-3.10.0-1160.el7.x86_64

WARNING - Conversion process interrupted and manual user intervention will be necessary.

Actually, I can't find a package named "system-release", then I tried manually replace the centos kernel by rhel kernel with the same version:
[root@localhost ~]# rpm -ihv /media/Packages/kernel-3.10.0-1160.el7.x86_64.rpm --force --nodeps

Then run convert2rhel again, this time it will give the error and exit again, it return another error(seems still lack of system-release package).

Continue with the system conversion? [y/n]: y
[01/31/2021 17:39:40] TASK - [Prepare: Gather system information] *******************************
[01/31/2021 17:39:40] CRITICAL - Error: Unable to find the /etc/system-release file containing the OS name and version
[01/31/2021 17:39:40] DEBUG - Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/convert2rhel/main.py", line 65, in main
    systeminfo.system_info.resolve_system_info()
  File "/usr/lib/python2.7/site-packages/convert2rhel/systeminfo.py", line 72, in resolve_system_info
    self.system_release_file_content = self._get_system_release_file_content()
  File "/usr/lib/python2.7/site-packages/convert2rhel/systeminfo.py", line 88, in _get_system_release_file_content
    return redhatrelease.get_system_release_content()
  File "/usr/lib/python2.7/site-packages/convert2rhel/redhatrelease.py", line 82, in get_system_release_content
    return utils.get_file_content(filepath)
  File "/usr/lib/python2.7/site-packages/convert2rhel/utils.py", line 76, in get_file_content
    if not os.path.exists(filename):
  File "/usr/lib64/python2.7/genericpath.py", line 18, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found

No changes were made to the system.

But If I manually install redhat-release-server package(which can help to resolve the dependency lack of "system-release"),  it complains" Current combination of system distribution and architecture is not supported for the conversion to RHEL" and exit. 

Would you pls verify it? Thx!

**Comment by jerry-wjl** [comment]
Copyright © 2010 Red Hat, Inc. All rights reserved. "Red Hat" and the Red Hat "Shadowman" logo are registered trademarks of Red Hat, Inc. "Linux" is a registered trademark of Linus Torvalds. All other trademarks are the property of their respective owners.

WARNING - By continuing you accept this EULA.

Continue with the system conversion? [y/n]: y



[01/31/2021 17:41:29] TASK - [Prepare: Gather system information] *******************************
Name:                Red Hat Enterprise Linux Server
OS major version:    7
[01/31/2021 17:41:29] DEBUG - Calling command 'uname -i'
Architecture:        x86_64
Config filename:     red-7-x86_64.cfg
[01/31/2021 17:41:29] CRITICAL - Current combination of system distribution and architecture is not supported for the conversion to RHEL.
[01/31/2021 17:41:29] DEBUG - Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/convert2rhel/main.py", line 65, in main
    systeminfo.system_info.resolve_system_info()
  File "/usr/lib/python2.7/site-packages/convert2rhel/systeminfo.py", line 79, in resolve_system_info
    self.cfg_content = self._get_cfg_content()
  File "/usr/lib/python2.7/site-packages/convert2rhel/systeminfo.py", line 117, in _get_cfg_content
    return self._get_cfg_section("system_info")
  File "/usr/lib/python2.7/site-packages/convert2rhel/systeminfo.py", line 127, in _get_cfg_section
    self.logger.critical("Current combination of system distribution"
  File "/usr/lib/python2.7/site-packages/convert2rhel/logger.py", line 105, in critical
    sys.exit(msg)
SystemExit: Current combination of system distribution and architecture is not supported for the conversion to RHEL.

No changes were made to the system.

**Comment by bocekm** [comment]
Hi @jerry-wjl, sorry for the troubles and thanks for taking the time for filing the issue.

The system-release package is actually an alias for the centos-release package on CentOS systems. On RHEL it is translated to redhat-release.

In order to allow convert2rhel to run again, copy the backed up /etc/system-release file to the original location (and overwrite the RHEL one you have there now):
`# cp /var/lib/convert2rhel/system-release /etc/`

Then, download and installed the recently released version 0.16: https://github.com/oamg/convert2rhel/releases/tag/v0.16. In this version we're reworked the way we treat the centos-release package during the conversion.

I've tried your scenario (CentOS 7.9 with kernel-3.10.0-1160.el7.x86_64) with the command `convert2rhel --disable-submgr --enablerepo rhel-7.9 --debug` and it runs fine with the latest convert2rhel version.

Let me know whether it works for you.

**Comment by jerry-wjl** [comment]
Hi Bocekm, Thanks for your update.

I tested the new version of convert2rhel(0.16), but hit the same issue as before. Pls check output below:

[02/09/2021 13:37:12] DEBUG - Downloading the kernel-3.10.0-1160.el7 package.
[02/09/2021 13:37:12] DEBUG - Calling command 'yumdownloader -v --destdir="/var/lib/convert2rhel/" --disablerepo="*" --enablerepo="rhel-7.9" --releasever=7Server kernel-3.10.0-1160.el7'
[02/09/2021 13:37:12] DEBUG - Pseudo-PTY columns set to: (0, 120)
Successfully downloaded the kernel-3.10.0-1160.el7 package.
[02/09/2021 13:37:13] DEBUG - Path of the downloaded package: /var/lib/convert2rhel/kernel-3.10.0-1160.el7.x86_64.rpm
Replacing CentOS Linux kernel-3.10.0-1160.el7 with RHEL kernel with the same NEVRA ... 
[02/09/2021 13:37:13] DEBUG - Calling command 'rpm -i --force --replacepkgs /var/lib/convert2rhel/kernel-3.10.0-1160.el7*'
CRITICAL - Unable to replace the kernel package: error: Failed dependencies:
	system-release is needed by kernel-3.10.0-1160.el7.x86_64

[02/09/2021 13:37:13] DEBUG - Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/convert2rhel/main.py", line 88, in main
    post_ponr_conversion()
  File "/usr/lib/python2.7/site-packages/convert2rhel/main.py", line 196, in post_ponr_conversion
    pkghandler.preserve_only_rhel_kernel()
  File "/usr/lib/python2.7/site-packages/convert2rhel/pkghandler.py", line 513, in preserve_only_rhel_kernel
    kernel_update_needed = install_rhel_kernel()
  File "/usr/lib/python2.7/site-packages/convert2rhel/pkghandler.py", line 553, in install_rhel_kernel
    handle_no_newer_rhel_kernel_available()
  File "/usr/lib/python2.7/site-packages/convert2rhel/pkghandler.py", line 575, in handle_no_newer_rhel_kernel_available
    replace_non_rhel_installed_kernel(installed[0])
  File "/usr/lib/python2.7/site-packages/convert2rhel/pkghandler.py", line 626, in replace_non_rhel_installed_kernel
    loggerinst.critical("Unable to replace the kernel package: %s" % output)
  File "/usr/lib/python2.7/site-packages/convert2rhel/logger.py", line 106, in critical
    sys.exit(msg)
SystemExit: Unable to replace the kernel package: error: Failed dependencies:
	system-release is needed by kernel-3.10.0-1160.el7.x86_64


WARNING - Conversion process interrupted and manual user intervention will be necessary.

I believe the job can go on if convert2rhel ignores the rpm dependency check when replace old kernel, that means the command:
'rpm -i --force --replacepkgs /var/lib/convert2rhel/kernel-3.10.0-1160.el7*'

should be modified to:
'rpm -i --force --nodeps --replacepkgs /var/lib/convert2rhel/kernel-3.10.0-1160.el7*'

So I grep and manually modified 2 py files:

1, /usr/lib/python2.7/site-packages/convert2rhel/pkghandler.py change the line below to:
'rpm -i --force --nodeps --replacepkgs %s*' % os.path.join(utils.TMP_DIR, pkg),

2, /usr/lib/python2.7/site-packages/convert2rhel/utils.py change the line below to:
cmd_param.append("--replacepkgs --nodeps")

Then recover the system-release from /var/lib/convert2rhel/backup and run the convert job again, then it works fine.

On the other hand, in my testing lab I found convert2rhel would hit dependency issue when the original centos server has abrt and libreport and relevant pkg installed, which may cause convert2rhel failed finally, so it should be removed before running convert2rhel, eg:

yum remove abrt-* libreport-*

Of course these pkgs can be installed after convert2rhel job successfully done. 

Below are some outputs:

Error: Package: libreport-web-2.1.11-53.el7.centos.x86_64 (@anaconda/7)
           Requires: libreport = 2.1.11-53.el7.centos
           Removing: libreport-2.1.11-53.el7.centos.x86_64 (@anaconda/7)
               libreport = 2.1.11-53.el7.centos
           Downgraded By: libreport-2.1.11-53.el7.x86_64 (rhel-7.9)
               libreport = 2.1.11-53.el7
Error: Package: libreport-cli-2.1.11-53.el7.centos.x86_64 (@anaconda/7)
           Requires: libreport = 2.1.11-53.el7.centos
           Removing: libreport-2.1.11-53.el7.centos.x86_64 (@anaconda/7)
               libreport = 2.1.11-53.el7.centos
           Downgraded By: libreport-2.1.11-53.el7.x86_64 (rhel-7.9)
               libreport = 2.1.11-53.el7
 You could try using --skip-broken to work around the problem
** Found 4 pre-existing rpmdb problem(s), 'yum check' output follows:
abrt-cli-2.1.11-60.el7.centos.x86_64 has missing requires of libreport-centos >= ('0', '2.1.11', '46')
abrt-cli-2.1.11-60.el7.centos.x86_64 has missing requires of libreport-plugin-mantisbt >= ('0', '2.1.11', '46')
abrt-desktop-2.1.11-60.el7.centos.x86_64 has missing requires of libreport-centos >= ('0', '2.1.11', '46')
abrt-desktop-2.1.11-60.el7.centos.x86_64 has missing requires of libreport-plugin-mantisbt >= ('0', '2.1.11', '46')


---> Package nettle.i686 0:2.7.1-8.el7 will be installed
--> Finished Dependency Resolution
Error: Package: abrt-retrace-client-2.1.11-60.el7.centos.x86_64 (@anaconda/7)
           Requires: abrt = 2.1.11-60.el7.centos
           Removing: abrt-2.1.11-60.el7.centos.x86_64 (@anaconda/7)
               abrt = 2.1.11-60.el7.centos
           Downgraded By: abrt-2.1.11-60.el7.x86_64 (rhel-7.9)
               abrt = 2.1.11-60.el7
 You could try using --skip-broken to work around the problem
** Found 4 pre-existing rpmdb problem(s), 'yum check' output follows:
abrt-cli-2.1.11-60.el7.centos.x86_64 has missing requires of libreport-centos >= ('0', '2.1.11', '46')
abrt-cli-2.1.11-60.el7.centos.x86_64 has missing requires of libreport-plugin-mantisbt >= ('0', '2.1.11', '46')
abrt-desktop-2.1.11-60.el7.centos.x86_64 has missing requires of libreport-centos >= ('0', '2.1.11', '46')
abrt-desktop-2.1.11-60.el7.centos.x86_64 has missing requires of libreport-plugin-mantisbt >= ('0', '2.1.11', '46')

**Comment by bocekm** [comment]
Hi Jerry, thanks for the suggestion. You're right. Under typical circumstances, kernel is installed using yum and with that the system-release/redhat-release pkg is installed as a dependency. However when the CentOS kernel and RHEL kernel have completely the same version, we install it through rpm which causes this error because system-release/redhat-release is not installed at that point.
I'll provide a fix for that shortly. By the way, the change to `utils.py` is not necessary as the function `install_pkgs` does not handle kernel.
And I'll check the abrt and others later on.

**Comment by bocekm** [comment]
The abrt-related error root cause: a package from a standard base CentOS repo is installed (in this case it's the abrt-retrace-client) but in RHEL it's available in the Optional repo which is typically not used/enabled for the conversion.

Details of the issue:

- installing abrt-cli on CentOS draws in the abrt-retrace-client
- abrt.x86_64 0:2.1.11-60.el7.centos is being downgraded to abrt.x86_64 0:2.1.11-60.el7 (yes, the additional .centos means for yum that it is a package of a higher version)
- abrt-retrace-client depends on the abrt.x86_64 0:2.1.11-60.el7.centos being downgraded, but since abrt-retrace-client is not available in the enabled base RHEL 7 repo, it is supposed to stay as is on the system => hence the conflict

Alternative workaround to removing the abrt package manually = enable the RHEL Optional repo (`convert2rhel --disable-submgr --disablerepo "*" --enablerepo rhel-7-server-rpms --enablerepo=rhel-7-server-optional-rpms`).
