### ISSUE TITLE
yum related warning after conversion

### ISSUE THREAD

**Issue by WittyNameHere** [oamg/convert2rhel#175]
Converted CentOS 8.3 today with version 0.16. Seems to have went well, except any yum-based command now brings this error that wasn't happening in CentOS:

```
$ sudo dnf repolist
Updating Subscription Management repositories.
/usr/local/lib/python3.6/site-packages/dateutil/parser/_parser.py:70: UnicodeWarning: decode() called on unicode string, see https://bugzilla.redhat.com/show_bug.cgi?id=1693751
  instream = instream.decode()
```
This bug has apparently been around for a while upstream through the years in previous versions such as 8.1, and I'm not sure if convert2rhel is responsible or simply worked as intended, since I know it does a ton of rpm-related work. Since I only have one machine to work with I figured I'd ask if anyone else can test. But I'll reiterate, the system I converted wasn't doing this before.

**Comment by WittyNameHere** [comment]
There are 10 instances of the UnicodeWarning in my install log (attached file). It appears the first instance came when replacing the kernel with RHEL kernel.


```
Running transaction
  Preparing        :                                                        1/1 
  Installing       : kernel-core-4.18.0-240.8.1.el8_3.x86_64                1/6 
  Running scriptlet: kernel-core-4.18.0-240.8.1.el8_3.x86_64                1/6 
  Installing       : kernel-modules-4.18.0-240.8.1.el8_3.x86_64             2/6 
  Running scriptlet: kernel-modules-4.18.0-240.8.1.el8_3.x86_64             2/6 
  Installing       : kernel-4.18.0-240.8.1.el8_3.x86_64                     3/6 
  Erasing          : kernel-4.18.0-193.28.1.el8_2.x86_64                    4/6 
  Running scriptlet: kernel-4.18.0-193.28.1.el8_2.x86_64                    4/6 
  Erasing          : kernel-modules-4.18.0-193.28.1.el8_2.x86_64            5/6 
  Running scriptlet: kernel-modules-4.18.0-193.28.1.el8_2.x86_64            5/6 
  Running scriptlet: kernel-core-4.18.0-193.28.1.el8_2.x86_64               6/6 
sed: can't read /etc/system-release: No such file or directory

  Erasing          : kernel-core-4.18.0-193.28.1.el8_2.x86_64               6/6 
  Running scriptlet: kernel-core-4.18.0-193.28.1.el8_2.x86_64               6/6 
  Running scriptlet: kernel-core-4.18.0-240.8.1.el8_3.x86_64                6/6 
sed: can't read /etc/system-release: No such file or directory

  Running scriptlet: kernel-core-4.18.0-193.28.1.el8_2.x86_64               6/6 
  Verifying        : kernel-modules-4.18.0-240.8.1.el8_3.x86_64             1/6 
  Verifying        : kernel-core-4.18.0-240.8.1.el8_3.x86_64                2/6 
  Verifying        : kernel-4.18.0-240.8.1.el8_3.x86_64                     3/6 
  Verifying        : kernel-4.18.0-193.28.1.el8_2.x86_64                    4/6 
  Verifying        : kernel-core-4.18.0-193.28.1.el8_2.x86_64               5/6 
  Verifying        : kernel-modules-4.18.0-193.28.1.el8_2.x86_64            6/6/usr/local/lib/python3.6/site-packages/dateutil/parser/_parser.py:70: UnicodeWarning: decode() called on unicode string, see https://bugzilla.redhat.com/show_bug.cgi?id=1693751
  instream = instream.decode()

 
Installed products updated.

Installed:
  kernel-4.18.0-240.8.1.el8_3.x86_64                                            
  kernel-core-4.18.0-240.8.1.el8_3.x86_64                                       
  kernel-modules-4.18.0-240.8.1.el8_3.x86_64                                    

Removed:
  kernel-4.18.0-193.28.1.el8_2.x86_64                                           
  kernel-core-4.18.0-193.28.1.el8_2.x86_64                                      
  kernel-modules-4.18.0-193.28.1.el8_2.x86_64                                   

Complete!
```

[convert2rhel.log](https://github.com/oamg/convert2rhel/files/5929240/convert2rhel.log)

**Comment by WittyNameHere** [comment]
Used Convert2RHEL on a friend's CentOS 8.3 install today and he doesn't have this problem, so I don't know anymore. Tried having DNF reinstall `python3-dateutil` and `rpm` in hopes that might fix it, but it didn't.

**Comment by ZhukovGreen** [comment]
Hi @WittyNameHere, could you please attach the conversion log (stored at /var/log/convert2rhel/convert2rhel.log)

**Comment by SpyTec** [comment]
Looking through the logfile now and nothing stands out, you're right it happens very early on when installing kernel. 

Not been successful yet in getting a reproducible VM. 

From what I've gathered so far it is definitely a leftover from the migration, there's been similar issues over at leapp. 

You should just be able to _delete_ `dateutil` and it will sort it out, but use your best judgement

`rm -rf /usr/local/lib/python3.6/site-packages/dateutil`

**Comment by WittyNameHere** [comment]
Removed those files and rebooted, but sadly it's still happening.

I realized today that I had previously attempted to run the script only to back out when prompted early in the procedure, and that this wasn't included in my log file because there weren't any occurrences of the message until my final run. But here's the log from my aborted runs in case they might help.

[convert2rhel.log](https://github.com/oamg/convert2rhel/files/5968386/convert2rhel.log)

**Comment by SpyTec** [comment]
Hm. Are you getting a different error after removing that folder? You shouldn't be getting an error pointing to files that no longer exist

**Comment by ZhukovGreen** [comment]
@WittyNameHere I just tried the upgrade the CentOS8.3 which has the python3-dateutil package installed. The upgrade passes successfully, and I can't reproduce your issue. Moreover I see that dnf install python3-dateutil in other location compared to log:
```
Python 3.6.8 (default, Aug 18 2020, 08:33:21) 
[GCC 8.3.1 20191121 (Red Hat 8.3.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dateutil
>>> dateutil.__path__
['/usr/lib/python3.6/site-packages/dateutil']
```
Also, this package doesn't have _parser.py module.

**Comment by WittyNameHere** [comment]
@SpyTec Yes, it's still calling those modules but now can't find them.

> Failed loading plugin "changelog": No module named 'dateutil'
> Failed loading plugin "product-id": No module named 'dateutil'
> Failed loading plugin "subscription-manager": No module named 'dateutil'
> Failed loading plugin "upload-profile": No module named 'dateutil'
> Last metadata expiration check: 2:23:23 ago on Fri 12 Feb 2021 07:05:31 AM PST.
> Dependencies resolved.
> Nothing to do.

**Comment by WittyNameHere** [comment]
Okay, I fixed it!

It was indeed an out-of-date pip3 related package. Having pip3 get a list of outdated packages and reinstall has fixed the issue.
