### ISSUE TITLE
** Found 4 pre-existing rpmdb problem(s), 'yum check' output follows:

### ISSUE THREAD

**Issue by dpconners** [oamg/convert2rhel#200]
Using VMware clones of a newly built "server with GUI" Centos 7 to work out convert2rhel to RHEL7.
Pre update: on one of the clones 'yum check' reveals no issues.

***On this particular run I set skip_broken=1 in /etc/yum.conf on the theroy I could just address any issues later - it did not seem to have the effect***

**In my examples below I'm working 2 clones:  
On "Trane" - convert2rhel was executed and failed.
On "dhcp189" - convert2rhel has not been run.**

Pre convert2rhel
[root@dhcp189 ~]# yum check
Loaded plugins: fastestmirror, langpacks
check all

Steps followed to run convert2rhel:
On the VM to be converted:
[root@Trane ~]# yum install -y https://github.com/oamg/convert2rhel/releases/download/v0.17/convert2rhel-0.17-1.el7.noarch.rpm 
[root@Trane ~]# yum install tmux -y 
[root@Trane ~]# tmux new -s convert
[root@Trane ~]# yum update -y
[root@Trane ~]# reboot
[root@Trane ~]# convert2rhel --disable-submgr --enablerepo rhel-7-server-rpms --debug  

Here's where it breaks.
Error: Package: abrt-retrace-client-2.1.11-60.el7.centos.x86_64 (@anaconda/7)
Requires: abrt = 2.1.11-60.el7.centos
Removing: abrt-2.1.11-60.el7.centos.x86_64 (@anaconda/7)
abrt = 2.1.11-60.el7.centos
Downgraded By: abrt-2.1.11-60.el7.x86_64 (rhel-7-server-rpms)
abrt = 2.1.11-60.el7
Available: abrt-2.1.11-12.el7.x86_64 (rhel-7-server-rpms)
abrt = 2.1.11-12.el7
Available: abrt-2.1.11-19.el7.x86_64 (rhel-7-server-rpms)
abrt = 2.1.11-19.el7
Available: abrt-2.1.11-22.el7_1.x86_64 (rhel-7-server-rpms)
abrt = 2.1.11-22.el7_1
Available: abrt-2.1.11-34.el7.x86_64 (rhel-7-server-rpms)
abrt = 2.1.11-34.el7
Available: abrt-2.1.11-35.el7.x86_64 (rhel-7-server-rpms)
abrt = 2.1.11-35.el7
Available: abrt-2.1.11-45.el7.x86_64 (rhel-7-server-rpms)
abrt = 2.1.11-45.el7
Available: abrt-2.1.11-48.el7.x86_64 (rhel-7-server-rpms)
abrt = 2.1.11-48.el7
Available: abrt-2.1.11-50.el7.x86_64 (rhel-7-server-rpms)
abrt = 2.1.11-50.el7
Available: abrt-2.1.11-52.el7.x86_64 (rhel-7-server-rpms)
abrt = 2.1.11-52.el7
Available: abrt-2.1.11-55.el7.x86_64 (rhel-7-server-rpms)
abrt = 2.1.11-55.el7
Available: abrt-2.1.11-57.el7.x86_64 (rhel-7-server-rpms)
abrt = 2.1.11-57.el7
You could try using --skip-broken to work around the problem
** Found 4 pre-existing rpmdb problem(s), 'yum check' output follows:
abrt-cli-2.1.11-60.el7.centos.x86_64 has missing requires of libreport-centos >= ('0', '2.1.11', '46')
abrt-cli-2.1.11-60.el7.centos.x86_64 has missing requires of libreport-plugin-mantisbt >= ('0', '2.1.11', '46')
abrt-desktop-2.1.11-60.el7.centos.x86_64 has missing requires of libreport-centos >= ('0', '2.1.11', '46')
abrt-desktop-2.1.11-60.el7.centos.x86_64 has missing requires of libreport-plugin-mantisbt >= ('0', '2.1.11', '46')
 
Seems to be a naming or numbering convention issue for libreport-centos and  libreport-plugin-mantisbt
[root@Trane ~]# rpm -qa | grep libreport
libreport-python-2.1.11-53.el7.centos.x86_64
libreport-plugin-bugzilla-2.1.11-53.el7.centos.x86_64
libreport-cli-2.1.11-53.el7.centos.x86_64
libreport-filesystem-2.1.11-53.el7.centos.x86_64
libreport-plugin-reportuploader-2.1.11-53.el7.centos.x86_64
libreport-plugin-mailx-2.1.11-53.el7.centos.x86_64
libreport-anaconda-2.1.11-53.el7.centos.x86_64
**libreport-2.1.11-53.el7.centos.x86_64**
libreport-plugin-ureport-2.1.11-53.el7.centos.x86_64
libreport-web-2.1.11-53.el7.centos.x86_64
libreport-rhel-anaconda-bugzilla-2.1.11-53.el7.centos.x86_64
libreport-gtk-2.1.11-53.el7.centos.x86_64
libreport-plugin-rhtsupport-2.1.11-53.el7.centos.x86_64

On the clone that of this machine pre convert2rhel, the "missing" packages were already installed.

[root@dhcp189 ~]# yum install libreport-plugin-mantisbt
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: mirror.net.cen.ct.gov
 * extras: mirror.vcu.edu
 * updates: mirrors.tripadvisor.com
Package libreport-plugin-mantisbt-2.1.11-53.el7.centos.x86_64 already installed and latest version
Nothing to do
[root@dhcp189 ~]# yum install libreport-centos
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: mirror.net.cen.ct.gov
 * extras: mirror.vcu.edu
 * updates: mirrors.tripadvisor.com
Package libreport-centos-2.1.11-53.el7.centos.x86_64 already installed and latest version

[root@dhcp189 ~]# rpm -qa | grep libreport-centos
libreport-centos-2.1.11-53.el7.centos.x86_64
[root@dhcp189 ~]# rpm -qa | grep libreport-plugin-mantisbt
libreport-plugin-mantisbt-2.1.11-53.el7.centos.x86_64
Nothing to do
[root@dhcp189 ~]# rpm -qa | grep libreport-centos
libreport-centos-2.1.11-53.el7.centos.x86_64
[root@dhcp189 ~]# rpm -qa | grep libreport-plugin-mantisbt
libreport-plugin-mantisbt-2.1.11-53.el7.centos.x86_64

But on the machine where the covert2rhel failed the packages have been removed?
[root@Trane ~]# rpm -qa | grep libreport-centos
[root@Trane ~]# rpm -qa | grep libreport-plugin-mantisbt
[root@Trane ~]# 

I uploaded the log file.

[convert2rhel.log](https://github.com/oamg/convert2rhel/files/6095412/convert2rhel.log)

And a question.  Suppose I encounter a problem like this and want to fix it, and restart the convert.
(Maybe uninstalling the offending packages to deal with them later?)
What is the magic that lets me restart?

[root@Trane ~]# convert2rhel --disable-submgr --enablerepo rhel-7-server-rpms --debug --restart
[03/06/2021 08:55:38] TASK - [Prepare: Gather system information] *******************************
Name:                Red Hat Enterprise Linux Server
OS version:          7.9
[03/06/2021 08:55:38] DEBUG - Calling command 'uname -i'
Architecture:        x86_64
Config filename:     red-7-x86_64.cfg
CRITICAL - Current combination of system distribution and architecture is not supported for the conversion to RHEL.

And another question.
Is there a "yum check" type command I could run before  convert2rhel that wold have alerted me to the issue?

And finally -  as I read the logfile, I missed this on screen:

[03/05/2021 14:10:56] TASK - [Prepare: Gather system information] *******************************
Name:                CentOS Linux
OS version:          7.9
[03/05/2021 14:10:56] DEBUG - Calling command 'uname -i'
Architecture:        x86_64
Config filename:     centos-7-x86_64.cfg
Running the 'rpm -Va' command which can take several minutes. It can be disabled by using the --no-rpm-va option.
[03/05/2021 14:10:56] DEBUG - Calling command 'rpm -Va'
[03/05/2021 14:10:59] DEBUG - Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/convert2rhel/main.py", line 65, in main
    systeminfo.system_info.resolve_system_info()
  File "/usr/lib/python2.7/site-packages/convert2rhel/systeminfo.py", line 88, in resolve_system_info
    self.generate_rpm_va()
  File "/usr/lib/python2.7/site-packages/convert2rhel/systeminfo.py", line 190, in generate_rpm_va
    rpm_va, _ = utils.run_subprocess("rpm -Va", print_output=False)
  File "/usr/lib/python2.7/site-packages/convert2rhel/utils.py", line 142, in run_subprocess
    for line in iter(process.stdout.readline, b''):
KeyboardInterrupt

No changes were made to the system.

And above - shouldn't I have been warned that a script failed?

Thanks for looking at this,

David

**Comment by dpconners** [comment]
Apologies - this log also contains a run that was aborted because I specified a custom repo incorrectly "rhev".  Subsequent runs were "convert2rhel --disable-submgr --enablerepo rhel-7-server-rpms --debug"  so the last question o mine is bogus, and the log is cluttered at the beginning with my mistake.

**Comment by dpconners** [comment]
**Double apology** - as I re-read all of this I believe my convert2rhel syntax was totally bogus having evolved from earlier attempts to use a custom repo.  I'm going  to try another run on a clean machine as follows.

# convert2rhel  --debug

I'll add to this comment with my results.

**Comment by dpconners** [comment]
Problem persists - less confusion I hope this time.
One issue, my "Red Hat Enterprise Linux for Virtual Datacenters, Standard" is not letting new machine register, I opened a ticket with RedHat and got around that issue today by unregistering a physical machine and letting this VM grab that entitlement.  It worked, and the convert2rhel proceeded.

[root@dhcp189 log]# convert2rhel  --debug

I'm attaching a zip file problems.zip containing, logs and text files showing the varying states of the rpms later missing. (greps of the logs in /var/log/convert2rhel)
**convert2rhel.log**
**rpm_va.log**
$ grep libreport-plugin-mantisbt * > **libreport-plugin-mantisbt.txt**  
$ grep libreport-centos * > **libreport-centos.txt**

Regards,

David

**Comment by dpconners** [comment]
I seem to be  a day late and a dollar short - read to the bottom of "Fail when convert CentOS 7.9 to RHEL 7.9 #166"  and I see that my dependency issue understood and work in progress.  I'll work with that and keep an eye out for developments.

**Comment by bocekm** [comment]
Hi @dpconners, thanks for the time you're taking to report the issues.

The libreport-centos and libreport-plugin-mantisbt are being removed by convert2rhel:
https://github.com/oamg/convert2rhel/blob/v0.17/convert2rhel/data/7/x86_64/configs/centos-7-x86_64.cfg#L16

That indeed causes the conversion to fail when the abrt package is installed. As you found out, we have got that reported [some time ago](https://github.com/oamg/convert2rhel/issues/166#issuecomment-775693251) yet haven't got to it yet.

As a workaround for that issue you can uninstall the abrt package manually before executing convert2rhel and install it back after the conversion.

**Comment by dpconners** [comment]
Hi @bocekm,  Thanks for all your efforts!  I took what I learned from that other ticket and have succeeded with a  couple of converts.  

VMware VM using RedHat Credentials (convert2rhel --debug) and a VMware VM using a local repo. (convert2rhel --disable-submgr --enablerepo rhel-7-server-rpms --debug --disable-colors   --no-rpm-va )

In progress - "convert2rhel --disable-submgr --enablerepo rhel-7-server-rpms --debug --disable-colors   --no-rpm-va" on a KVM VM configured as UEFI boot.  Having been alerted by https://bugzilla.redhat.com/show_bug.cgi?id=1898314 I wanted to test that "solution".

Is it still the case that the workaround on that page is still needed?  

Regards,

David

**Comment by dpconners** [comment]
Nothing but success now.  Thanks again for your efforts. I'm solid now - do we close this?

My notes for convert2rhel of a (remote) KVM VM configured with UEFI boot, and using a local RedHat repo.

Assumes that the rhev.repo file has been copied to /etc/yum.repos.d/rhev.repo 

# yum install tmux -y
# yum install -y https://github.com/oamg/convert2rhel/releases/download/v0.17/convert2rhel-0.17-1.el7.noarch.rpm
# yum erase abrt -y
# yum erase libreport -y
# yum update -y
# reboot
# tmux new -s convert
# convert2rhel --disable-submgr --enablerepo rhel-7-server-rpms --debug --disable-colors --no-rpm-va
#
####  Do NOT reboot until the boot record is fixed. (may or may not still be needed?)  ####
#
# grub2-mkconfig -o /boot/efi/EFI/redhat/grub.cfg
# efibootmgr
# efibootmgr -Bb 0004
# efibootmgr -c -d /dev/sda -p 1 -l \\EFI\\redhat\\shimx64.efi -L "Red Hat Enterprise Linux 7"
# efibootmgr -v
# yum --enablerepo rhel-7-server-rpms install abrt
#
# reboot
