### ISSUE TITLE
Update the copyright year

### ISSUE THREAD

**Issue by ZhukovGreen** [oamg/convert2rhel#208]
Nit: we need to update the copyright year. It is 2021 already

_Originally posted by @ZhukovGreen in https://github.com/oamg/convert2rhel/pull/196#discussion_r595838151_

**Comment by bocekm** [comment]
We don't need to. I was checking that some time ago and I'd need to find relevant resources to back that opinion, but I remember that the copyright year does not need to be regularly updated to have the code under the copyright.

**Comment by bocekm** [comment]
For me this reddit thread is enough https://stackoverflow.com/questions/2390230/do-copyright-dates-need-to-be-updated.
