### ISSUE TITLE
RFE: centos8 -> rhel8

### ISSUE THREAD

**Issue by fche** [oamg/convert2rhel#24]
While centos8 is new, there may still be those who'd like to switch to the real thing.

**Comment by bocekm** [comment]
Thanks @fche for your input. I'm sorry I forgot to reply to you here. I passed your request to the project management already the day you posted it. It's being evaluated.

**Comment by bocekm** [comment]
We're working on this RFE. The first step is being done under: https://github.com/oamg/convert2rhel/pull/82.
Internal tracking Jira task: OAMG-3012
