### ISSUE TITLE
CentOS 6.10 with Python 2.6.6 fail at reboot (overwriting env vars)

### ISSUE THREAD

**Issue by GeorgeDuckman** [oamg/convert2rhel#241]
When I run the script it ends in an error near the end when it tries to restart the server.

Here is the error :

> [03/30/2021 10:34:25] TASK - [Final: Non-interactive mode] **************************************
> For the non-interactive use of the tool, run the following command:
> convert2rhel --disable-submgr  --disablerepo=*  --enablerepo=redhat  -y
> 
> 
> ('[%s] %s - %s', '03/30/2021 10:34:25', 'DEBUG', "Calling command 'reboot'")
> Traceback (most recent call last):
>   File "/usr/lib/python2.6/site-packages/convert2rhel/main.py", line 109, in main
>     utils.restart_system()
>   File "/usr/lib/python2.6/site-packages/convert2rhel/utils.py", line 117, in restart_system
>     run_subprocess("reboot")
>   File "/usr/lib/python2.6/site-packages/convert2rhel/utils.py", line 140, in run_subprocess
>     env={'LC_ALL': 'C'})
>   File "/usr/lib64/python2.6/subprocess.py", line 642, in __init__
>     errread, errwrite)
>   File "/usr/lib64/python2.6/subprocess.py", line 1238, in _execute_child
>     raise child_exception
> OSError: [Errno 2] No such file or directory
> 
> WARNING - Conversion process interrupted and manual user intervention will be necessary.
> 

I tried with versions 0.20 and 0.19 of the script. I checked that the reboot command existed, but after some testing from a python console I noticed that it worked by removing the "env={'LC_ALL': 'C'}" parameter from the subprocess.popen command.

**Comment by ZhukovGreen** [comment]
Thx @GeorgeDuckman We'll look into this and let you know

**Comment by ZhukovGreen** [comment]
@fellipeh I see that this env={'LC_ALL': 'C'} in run_subprocess was introduced in   https://github.com/oamg/convert2rhel/pull/83. Any ideas around this issue?

**Comment by ZhukovGreen** [comment]
Tracked under https://issues.redhat.com/browse/OAMG-4719

**Comment by ZhukovGreen** [comment]
Hi @GeorgeDuckman, are you unable to extract the conversion logs from the unbootable machine (located at /var/log/convert2rhel/convert2rhel.log). Thank you

**Comment by GeorgeDuckman** [comment]
Hello @ZhukovGreen, below the requested file, I had to delete some lines for professional reasons:

[convert2rhel.log](https://github.com/oamg/convert2rhel/files/6284148/temp.txt)

Thank you.

**Comment by ZhukovGreen** [comment]
@oamg/Convert2RHEL it seems @GeorgeDuckman hit a bug. From the log, I see that convert2rhel runs `reboot` command which doesn't exists on centos6.

**Comment by ZhukovGreen** [comment]
Thanks @GeorgeDuckman, we'll notify you of fixing this. However, it might unblock you, if you will run the convert2rhel utility without -r option:
    -r, --restart       Restart the system when it is successfully converted
                        to RHEL to boot the new RHEL kernel.

**Comment by GeorgeDuckman** [comment]
@ZhukovGreen Yes the manual reboot works.
Thanks

**Comment by ZhukovGreen** [comment]
@GeorgeDuckman could you please check output on the centos6 host which is failing to convert:
```
echo $PATH
ls /sbin/reboot
ls /sbin/shutdown
```

**Comment by GeorgeDuckman** [comment]
@ZhukovGreen I'll see to revert the host to a CentOS 6 server as soon as possible.

But if it helps, in my first post I said that the reboot command exists, I managed to use it from the command line. I then reproduced the code of the reboot function of convert2rhel and the reboot command is well executed by removing the "env={'LC_ALL': 'C'}" parameter part, which is surprising I admit.

**Comment by bocekm** [comment]
I was able to reproduce the issue in the [CentOS 6.10 vagrant box](https://app.vagrantup.com/eurolinux-vagrant/boxes/centos-6) we use for testing and development with just using `-r` option. The above I recommended ("/sbin/reboot") fixed that.

**Comment by pirat89** [comment]
The explanation of the root cause is here: https://github.com/oamg/convert2rhel/pull/251/files#r616752752

**Comment by GeorgeDuckman** [comment]
Sorry for the wait.
Here is some more information : 

```
[root@serv~]# whereis reboot
reboot: /sbin/reboot /usr/share/man/man2/reboot.2.gz /usr/share/man/man8/reboot.8.gz

[root@serv~]# whereis shutdown
shutdown: /sbin/shutdown /usr/share/man/man3p/shutdown.3p.gz /usr/share/man/man2/shutdown.2.gz /usr/share/man/man8/shutdown.8.gz
```

And thanks @bocekm and @pirat89 , I tried replacing "reboot" with "/sbin/reboot" and it works flawlessly now. Here's the tiny script I used to test it :

```python
import subprocess
import sys
import shlex

def run_subprocess(cmd="", print_cmd=True, print_output=True):
    """Call the passed command and optionally log the called command (print_cmd=True) and its
    output (print_output=True). Switching off printing the command can be useful in case it contains
    a password in plain text.
    """
    if print_cmd:
        print("Calling command '%s'" % cmd)

    # Python 2.6 has a bug in shlex that interprets certain characters in a string as
    # a NULL character. This is a workaround that encodes the string to avoid the issue.
    if sys.version_info[0] == 2 and sys.version_info[1] == 6:
        cmd = cmd.encode("ascii")
    cmd = shlex.split(cmd, False)
    process = subprocess.Popen(cmd,
                               stdout=subprocess.PIPE,
                               stderr=subprocess.STDOUT,
                               bufsize=1,
                               env={'LC_ALL': 'C'})
    output = ''
    for line in iter(process.stdout.readline, b''):
        output += line.decode()
        if print_output:
            print(line.decode().rstrip('\n'))

    # Call communicate() to wait for the process to terminate so that we can get the return code by poll().
    # It's just for py2.6, py2.7+/3 doesn't need this.
    process.communicate()

    return_code = process.poll()
    return output, return_code

run_subprocess("/sbin/reboot")
```
