### ISSUE TITLE
RFE: Adding preconvert option

### ISSUE THREAD

**Issue by tjyang** [oamg/convert2rhel#243]
Hi 
Like --preupgrade option in  leapp application, Can you add option --preconvert  ?

**Comment by bocekm** [comment]
Hi T.J.
Thanks for the suggestion. There's not many checks of the system that convert2rhel does now (compared to leapp which has tens of them). But we plan on adding more check going forward and having an option to run just the pre-conversion checks will become more valuable. We'll keep an eye on this feature request.

**Comment by bocekm** [comment]
This has been implemented by https://github.com/oamg/convert2rhel/pull/761, https://github.com/oamg/convert2rhel/pull/820, and a couple of PRs in between.
You can now read about the pre-conversion analysis feature at https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/converting_from_an_rpm-based_linux_distribution_to_rhel/index#reviewing-the-pre-conversion-analysis-report_converting-from-a-linux-distribution-to-rhel.
