### ISSUE TITLE
subscription-manager directory does not exist

### ISSUE THREAD

**Issue by Eric-Sparks** [oamg/convert2rhel#257]
My conversion is failing after TASK: [Convert: Subscription Manager - Install].

I get a "CRITICAL - The /usr/share/convert2rhel/subscription-manager directory does not exist or is empty." error.  The only way I can see there being something in this directory is if I'm using a satellite instance but I'm trying to use RHSM and the docs don't say anything about putting anything in that directory when using that resource.  Am I missing something?

Trying this on CentOS 8.  Thanks!

**Comment by ZhukovGreen** [comment]
@Eric-Sparks thank you for reporting this issue. Could you send us the logs (/var/log/convert2rhel/convert2rhel.log.

**Comment by bocekm** [comment]
Hi @Eric-Sparks, just to be sure, are you using the latest version 0.20 from https://ftp.redhat.com/redhat/convert2rhel/8/?

**Comment by Eric-Sparks** [comment]
@bocekm That was the problem.  Despite having added the convert2rhel repo, yum had installed version 0.13 from EPEL.  I was able to switch out the versions and the conversion went as planned.  Thanks for the quick replies!
