### ISSUE TITLE
Command `convert2rhel --help` returns 1 exit code 

### ISSUE THREAD

**Issue by sturivny** [oamg/convert2rhel#26]
Both `convert2rhel -h` and `convert2rhel --help` return 1 exit code

**Comment by bocekm** [comment]
It was supposed to be fixed under https://github.com/oamg/convert2rhel/pull/15. I need to take a look at it again then.

**Comment by bocekm** [comment]
I believe you're are seeing this issue only with old packages. Not with the latest builds from the master branch. See https://github.com/oamg/convert2rhel/pull/11#issuecomment-603849042.
