### ISSUE TITLE
Can't get list of kernel modules.

### ISSUE THREAD

**Issue by Eric-Sparks** [oamg/convert2rhel#263]
Well, this is an interesting bug I've stumbled on.  This is on a CentOS 7 box that's been running for several years.  I get to a point where the script checks for kernel modules and then just fails.

From the logs:
```
[04/23/2021 04:02:05] TASK - [Convert: Final system checks before main conversion] **************
('[%s] %s - %s', '04/23/2021 04:02:05', 'DEBUG', "Calling command 'uname -r'")
5.11.9-x86_64-linode142
('[%s] %s - %s', '04/23/2021 04:02:05', 'DEBUG', 'Calling command \'find /lib/modules/5.11.9-x86_64-linode142 -name "*.ko*" -type f\'')
CRITICAL - Can't get list of kernel modules.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/convert2rhel/main.py", line 88, in main
    pre_ponr_conversion()
  File "/usr/lib/python2.7/site-packages/convert2rhel/main.py", line 208, in pre_ponr_conversion
    checks.perform_pre_ponr_checks()
  File "/usr/lib/python2.7/site-packages/convert2rhel/checks.py", line 83, in perform_pre_ponr_checks
    ensure_compatibility_of_kmods()
  File "/usr/lib/python2.7/site-packages/convert2rhel/checks.py", line 88, in ensure_compatibility_of_kmods
    host_kmods = get_installed_kmods()
  File "/usr/lib/python2.7/site-packages/convert2rhel/checks.py", line 135, in get_installed_kmods
    logger.critical("Can't get list of kernel modules.")
  File "/usr/lib/python2.7/site-packages/convert2rhel/logger.py", line 103, in _critical
    sys.exit(msg)
SystemExit: Can't get list of kernel modules.
```

I double-checked that directory and there are no .ko files in there.

**Comment by Eric-Sparks** [comment]
And, yes, this is running version 0.20.

**Comment by ZhukovGreen** [comment]
Hi, @Eric-Sparks could you reboot into Red Hat compatible kernel and try one more time? Instructions are here https://github.com/oamg/convert2rhel/pull/250/files#diff-cf19bc90f65d9e26e1b6fa7dcd84a18dfba097f65706e211a4f4ac71b1b467f6R306-R317 (actually very soon the conversion will be inhibited if non RHCK will be observed)

**Comment by bocekm** [comment]
@Eric-Sparks, the latest kernel provided in the CentOS 7 repos is `kernel-3.10.0-1160.24.1.el7.x86_64.rpm`. The same kernel is the latest on in RHEL 7 repos. Your CentOS 7 server is running  kernel 5.11.9. During the conversion to RHEL 7 the kernel would be downgraded to the kernel 3.10.0. This scenario is untested and possibly unsafe in the meaning that the server may not boot up, for example if the kernel 3.10.0 kernel modules do not support the server hardware.

I admit that this error is not what the tool should be printing. As @ZhukovGreen mentioned, after implementing https://github.com/oamg/convert2rhel/pull/250 we'll be requiring users to first boot the server with the kernel that is available in standard CentOS Linux/Oracle Linux repos. This step will allow them to see whether the server behaves correctly with such a kernel. Then the conversion will be allowed to proceed.

**Comment by bocekm** [comment]
Since the version [0.21](https://github.com/oamg/convert2rhel/releases/tag/v0.21), convert2rhel requires the system to be booted to a kernel of an equivalent version of the one in RHEL repos, signed by either Oracle or CentOS. If not, as it was in this case, the tool provides steps on how to do that.
