### ISSUE TITLE
Conversion to RHEL 8.3 / 8.4 stops after finding unsupported kernel modules in CentOS 8.3

### ISSUE THREAD

**Issue by deepak-c** [oamg/convert2rhel#277]
I have a CentOS 8.3 minimal instance running on a VMware Fusion to which I have applied all the available updates and rebooted the system.

Installed latest version of convert2rhel (v0.21), mounted RHEL 8.4 beta iso to a local mount dir path and ran the conversion with the following command:
```
convert2rhel --disable-submgr  --disablerepo=*  --enablerepo=InstallMedia-BaseOS  --enablerepo=InstallMedia-AppStream --debug
```
As part of the final checks, the conversion throws error with unsupporting kernel modules. Here is the part that was picked out from the full logs:

```
[05/14/2021 06:30:42] TASK - [Convert: Final system checks before main conversion] **************
[05/14/2021 06:30:42] DEBUG - Calling command 'uname -r'
4.18.0-240.22.1.el8_3.x86_64
[05/14/2021 06:30:42] DEBUG - Calling command 'find /lib/modules/4.18.0-240.22.1.el8_3.x86_64 -name "*.ko*" -type f'
[05/14/2021 06:30:42] DEBUG - Calling command 'repoquery --releasever=8 --setopt=module_platform_id=platform:el8 --repoid InstallMedia-BaseOS --repoid InstallMedia-AppStream -f /lib/modules/*.ko*'
[05/14/2021 06:30:43] DEBUG - Calling command 'repoquery --releasever=8 --setopt=module_platform_id=platform:el8 --repoid InstallMedia-BaseOS --repoid InstallMedia-AppStream -l kernel-core-0:4.18.0-293.el8.x86_64 kernel-debug-core-0:4.18.0-293.el8.x86_64 kernel-debug-modules-0:4.18.0-293.el8.x86_64 kernel-debug-modules-extra-0:4.18.0-293.el8.x86_64 kernel-modules-0:4.18.0-293.el8.x86_64 kernel-modules-extra-0:4.18.0-293.el8.x86_64 kmod-kvdo-0:6.2.4.26-76.el8.x86_64 kmod-redhat-oracleasm-8:2.0.8-11.el8.x86_64'
[05/14/2021 06:30:44] DEBUG - Calling command 'uname -r'
4.18.0-240.22.1.el8_3.x86_64
CRITICAL - The following kernel modules are not supported in RHEL:
/lib/modules/4.18.0-240.22.1.el8_3.x86_64/kernel/lib/livepatch/test_klp_state3.ko.xz
/lib/modules/4.18.0-240.22.1.el8_3.x86_64/kernel/drivers/iommu/amd_iommu_v2.ko.xz
/lib/modules/4.18.0-240.22.1.el8_3.x86_64/kernel/lib/livepatch/test_klp_state2.ko.xz
/lib/modules/4.18.0-240.22.1.el8_3.x86_64/kernel/arch/x86/events/intel/intel-rapl-perf.ko.xz
/lib/modules/4.18.0-240.22.1.el8_3.x86_64/kernel/drivers/net/wireless/realtek/rtw88/rtw88.ko.xz
/lib/modules/4.18.0-240.22.1.el8_3.x86_64/kernel/drivers/net/wireless/realtek/rtw88/rtwpci.ko.xz
/lib/modules/4.18.0-240.22.1.el8_3.x86_64/kernel/drivers/gpu/drm/cirrus/cirrus.ko.xz
/lib/modules/4.18.0-240.22.1.el8_3.x86_64/kernel/drivers/firmware/dcdbas.ko.xz
/lib/modules/4.18.0-240.22.1.el8_3.x86_64/kernel/drivers/dax/dax_hmem.ko.xz
/lib/modules/4.18.0-240.22.1.el8_3.x86_64/kernel/drivers/acpi/dptf/dptf_power.ko.xz
/lib/modules/4.18.0-240.22.1.el8_3.x86_64/kernel/drivers/pinctrl/intel/pinctrl-intel.ko.xz
/lib/modules/4.18.0-240.22.1.el8_3.x86_64/kernel/lib/livepatch/test_klp_state.ko.xz
Uninstall or disable them and run convert2rhel again to continue with the conversion.
[05/14/2021 06:30:44] DEBUG - Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/convert2rhel/main.py", line 87, in main
    pre_ponr_conversion()
  File "/usr/lib/python3.6/site-packages/convert2rhel/main.py", line 199, in pre_ponr_conversion
    checks.perform_pre_ponr_checks()
  File "/usr/lib/python3.6/site-packages/convert2rhel/checks.py", line 125, in perform_pre_ponr_checks
    ensure_compatibility_of_kmods()
  File "/usr/lib/python3.6/site-packages/convert2rhel/checks.py", line 151, in ensure_compatibility_of_kmods
    ).format(kmods=not_supported_kmods)
  File "/usr/lib/python3.6/site-packages/convert2rhel/logger.py", line 103, in _critical
    sys.exit(msg)
SystemExit: The following kernel modules are not supported in RHEL:
/lib/modules/4.18.0-240.22.1.el8_3.x86_64/kernel/lib/livepatch/test_klp_state3.ko.xz
/lib/modules/4.18.0-240.22.1.el8_3.x86_64/kernel/drivers/iommu/amd_iommu_v2.ko.xz
/lib/modules/4.18.0-240.22.1.el8_3.x86_64/kernel/lib/livepatch/test_klp_state2.ko.xz
/lib/modules/4.18.0-240.22.1.el8_3.x86_64/kernel/arch/x86/events/intel/intel-rapl-perf.ko.xz
/lib/modules/4.18.0-240.22.1.el8_3.x86_64/kernel/drivers/net/wireless/realtek/rtw88/rtw88.ko.xz
/lib/modules/4.18.0-240.22.1.el8_3.x86_64/kernel/drivers/net/wireless/realtek/rtw88/rtwpci.ko.xz
/lib/modules/4.18.0-240.22.1.el8_3.x86_64/kernel/drivers/gpu/drm/cirrus/cirrus.ko.xz
/lib/modules/4.18.0-240.22.1.el8_3.x86_64/kernel/drivers/firmware/dcdbas.ko.xz
/lib/modules/4.18.0-240.22.1.el8_3.x86_64/kernel/drivers/dax/dax_hmem.ko.xz
/lib/modules/4.18.0-240.22.1.el8_3.x86_64/kernel/drivers/acpi/dptf/dptf_power.ko.xz
/lib/modules/4.18.0-240.22.1.el8_3.x86_64/kernel/drivers/pinctrl/intel/pinctrl-intel.ko.xz
/lib/modules/4.18.0-240.22.1.el8_3.x86_64/kernel/lib/livepatch/test_klp_state.ko.xz
Uninstall or disable them and run convert2rhel again to continue with the conversion.

WARNING - Abnormal exit! Performing rollback ...
```
Attached the full logs with debug enabled for further information.

I originally tried with mounting the RHEL 8.3 dvd iso as that would be the obvious straight forward conversion from CentOS 8.3 but that also failed with similar error but throwing even bigger list of unsupported kernel modules. My thought was that since I am running the latest kernel version in CentOS 8.3 (4.18.0-240.22.1.el8_3.x86_64) where as RHEL 8.3 includes older version (4.18.0-240.el8_3.x86_64), I was under the impression that the downgrade could be causing the problem, hence I started trying with RHEL 8.4 beta which includes the later version of the kernel. But, in both instances, the result was the same albeit with different sets of unsupported kernel modules.

I am stumped at this point with no further options to try, any directions would be really appreciated.

Thanks much for your help !

[convert2rhel.log](https://github.com/oamg/convert2rhel/files/6477034/convert2rhel.log)

**Comment by ZhukovGreen** [comment]
@deepak-c thank you for reporting this issue. I had a subscribed machine and tried to check if these kmods are present in rhel 8.3 (with rhel-8-baseos and appstream repos only).
```
[root@c2r-20210421123125 inhibit-if-kmods-is-not-supported]# repoquery -f /lib/modules/4.18.0-240.22.1.el8_3.x86_64/kernel/drivers/gpu/drm/cirrus/cirrus.ko.xz
Updating Subscription Management repositories.
Repository rhel-8-for-x86_64-baseos-rpms is listed more than once in the configuration
Repository rhel-8-for-x86_64-appstream-rpms is listed more than once in the configuration
Last metadata expiration check: 0:07:35 ago on Fri 14 May 2021 07:46:30 AM UTC.
kernel-core-0:4.18.0-240.22.1.el8_3.x86_64
```
I also tried conversion with some kmods, from your logs and it went well. So I believe the issue is in absence of these kmods in the provided rhel ISO image.

Could you check with the repoquery that these modules are missing indeed (i.e. repoquery -f /lib/modules/4.18.0-240.22.1.el8_3.x86_64/kernel/drivers/gpu/drm/cirrus/cirrus.ko.xz)

**Comment by deepak-c** [comment]
@ZhukovGreen Thanks for looking at my reported issue. 

Here is the output for the command you had asked for:

```
# repoquery --disablerepo="*" --enablerepo=InstallMedia-BaseOS  --enablerepo=InstallMedia-AppStream -f /lib/modules/4.18.0-240.22.1.el8_3.x86_64/kernel/drivers/gpu/drm/cirrus/cirrus.ko.xz
Last metadata expiration check: 9:02:37 ago on Fri 14 May 2021 04:42:43 UTC.
# 
```

Those modules are not part of the mounted RHEL 8.4 beta iso.

**Comment by ZhukovGreen** [comment]
I am not sure how critical would it be to skip this check for your case. However during the next week I'll be working on a feature which will be allowing to skip certain checks. I will keep you updated.

@oamg/convert2rhel what do you think guys? What else can we do in this case?

**Comment by deepak-c** [comment]
Apologies but I am no expert to ascertain if these kernel modules can be disabled / uninstalled. Also, looking at the big list of missing kernel modules, I wonder why these modules would be missing in the standard iso image - our installation is a standard CentOS 8 minimal installation with no special configurations.

I understand that the upgrade works well when connecting to the RHSM portal, it works for me as well as I would imagine the subscription management portal is kept up to date with all available packages. However, the issue is when attaching a standard RHEL 8.3 / 8.4 iso as the installation source media for convert2rhel to work with. Our systems are air-gapped with no connection outside possible, so that rules out the options of connecting to the RHSM portal / satellite server to fetch the latest updates. 

To workaround the issue, I am trying to find if the latest updates from the RHSM portal can be bundled up as an iso that can further be mounted as a source for the conversion process to leverage upon. Any help or other ideas would be really appreciated here, thanks!

**Comment by bocekm** [comment]
Hi Deepak, we don't support the option of converting the system using an ISO. We don't even test that. The reason is that the ISO gets outdated quickly and when you update the CentOS Linux system to the latest available packages you can install newer packages than those available in the ISO. And that would lead to unnecessary package downgrades during the conversion. Yum package downgrade is generally an unsupported and untested package management action. And on top of that, the kernel module check expects the RHEL repos to contain the same or newer kernel release than the currently booted one.

All I can tell is that the kernel modules are available in RHEL repos. What you can do is to have a single RHEL system subscribed to RHSM and then create a mirror of the RHSM-provided RHEL repos to a USB/local web-server/FTP-server using a reposync (details: https://access.redhat.com/solutions/23016). And then provide the repo mirrors to convert2rhel on the airgapped CentOS Linux machines.

BTW, the repoquery command @ZhukovGreen suggested should not include the kernel version because we don't know what version is in the ISO. So run this instead:
```
# repoquery --disablerepo="*" --enablerepo=InstallMedia-BaseOS  --enablerepo=InstallMedia-AppStream -f /lib/modules/*kernel/drivers/gpu/drm/cirrus/cirrus.ko.xz
```

**Comment by bocekm** [comment]
Just to give you the idea about the kernel modules being available in RHEL:
```
 repoquery --releasever=8 --setopt=module_platform_id=platform:el8 --disablerepo "*" --repofrompath baseos,<RHEL 8.3 repo with latest package updates> -f /lib/modules/*kernel/lib/livepatch/test_klp_state.ko.xz
Added baseos repo from http://rhsm-pulp.corp.redhat.com/content/dist/rhel8/8.4/x86_64/baseos/os/
Last metadata expiration check: 19:37:30 ago on Mon 17 May 2021 11:20:17 PM CEST.
kernel-core-0:4.18.0-240.1.1.el8_3.x86_64
kernel-core-0:4.18.0-240.10.1.el8_3.x86_64
kernel-core-0:4.18.0-240.15.1.el8_3.x86_64
kernel-core-0:4.18.0-240.22.1.el8_3.x86_64
kernel-core-0:4.18.0-240.8.1.el8_3.x86_64
kernel-core-0:4.18.0-240.el8.x86_64
kernel-debug-core-0:4.18.0-240.1.1.el8_3.x86_64
kernel-debug-core-0:4.18.0-240.10.1.el8_3.x86_64
kernel-debug-core-0:4.18.0-240.15.1.el8_3.x86_64
kernel-debug-core-0:4.18.0-240.22.1.el8_3.x86_64
kernel-debug-core-0:4.18.0-240.8.1.el8_3.x86_64
kernel-debug-core-0:4.18.0-240.el8.x86_64
```

**Comment by tchung1970** [comment]
I confirm this issue exist on "production" RHEL 8.4 which was released today

[05/18/2021 14:54:13] TASK - [Convert: Final system checks before main conversion] **************
4.18.0-240.22.1.el8_3.x86_64
4.18.0-240.22.1.el8_3.x86_64
**CRITICAL - The following kernel modules are not supported in RHEL:
/lib/modules/4.18.0-240.22.1.el8_3.x86_64/kernel/drivers/net/wireless/realtek/rtw88/rtw88.ko.xz
/lib/modules/4.18.0-240.22.1.el8_3.x86_64/kernel/drivers/dax/dax_hmem.ko.xz
/lib/modules/4.18.0-240.22.1.el8_3.x86_64/kernel/arch/x86/events/intel/intel-rapl-perf.ko.xz
/lib/modules/4.18.0-240.22.1.el8_3.x86_64/kernel/drivers/iommu/amd_iommu_v2.ko.xz
/lib/modules/4.18.0-240.22.1.el8_3.x86_64/kernel/drivers/firmware/dcdbas.ko.xz
/lib/modules/4.18.0-240.22.1.el8_3.x86_64/kernel/drivers/net/wireless/realtek/rtw88/rtwpci.ko.xz
/lib/modules/4.18.0-240.22.1.el8_3.x86_64/kernel/lib/livepatch/test_klp_state.ko.xz
/lib/modules/4.18.0-240.22.1.el8_3.x86_64/kernel/drivers/acpi/dptf/dptf_power.ko.xz
/lib/modules/4.18.0-240.22.1.el8_3.x86_64/kernel/lib/livepatch/test_klp_state2.ko.xz
/lib/modules/4.18.0-240.22.1.el8_3.x86_64/kernel/drivers/pinctrl/intel/pinctrl-intel.ko.xz
/lib/modules/4.18.0-240.22.1.el8_3.x86_64/kernel/lib/livepatch/test_klp_state3.ko.xz
/lib/modules/4.18.0-240.22.1.el8_3.x86_64/kernel/drivers/gpu/drm/cirrus/cirrus.ko.xz
Uninstall or disable them and run convert2rhel again to continue with the conversion.**
WARNING - Abnormal exit! Performing rollback ...
[05/18/2021 14:54:28] TASK - [Rollback: RHSM-related actions] ***********************************
Unregistering the system.
System unregistered successfully.

**Comment by bocekm** [comment]
@deepak-c, @tchung1970, indeed the conversion of CentOS/Oracle Linux 8 is not possible at this moment for the reason that the latest CentOS/Oracle Linux 8.3 kernel differs from the RHEL 8.4 kernel.
Please wait till CentOS/Oracle Linux 8.4 is released and then update to it. The conversion won't get stopped on the kernel modules after that.

**Comment by bocekm** [comment]
@deepak-c, we found out that the conversion from CentOS Linux 8.3 to RHEL 8.4 is not possible. What's possible is a conversion to RHEL 8.3 at this moment.
You mentioned your systems are air-gapped and no removable media are feasible. I hope that the systems can connect at least to other systems within the internal network. Then what's left is either setting up your own Red Hat Satellite instance to which your CentOS Linux systems would connect over the internal network. Or set up a simple nginx/apache web-server that would be serving RHEL 8.3 repos.
Note though, as I mentioned earlier, that the RHEL 8.3 repos need to contain the latest package updates for RHEL 8.3. The RHEL 8.3 ISO is 6 months old and many package updates have been released since then.

**Comment by deepak-c** [comment]
Thanks for the explanation, I understand setting up a satellite server is an option but unfortunately, it won't work for us as our RHEL instances are run by various customers worldwide who often don't have access to any internet outside. They are able to fetch software updates from our update server which includes the OS security updates and application updates which will then be installed through our pre-defined software update process. It is a very tightly controlled process here hence why it is a challenge to deviate any further from this process to achieve the conversion by any other process. 

I am not sure waiting for CentOS 8.4 is an option as there is no definite timeframe for that and we are running on a tight timelines here to deliver this conversion.

**Comment by NISHCHITHA-N** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1962193

Here it is.

**Comment by pixel-paul** [comment]
Hi,

So if you're on CentOS 8.4, it is currently not possible to go to RHEL 8.4?

Thanks,

Paul

**Comment by bocekm** [comment]
@pixel-paul, you can, with the following workaround described in https://bugzilla.redhat.com/show_bug.cgi?id=1971042#c1. In a nutshell it requires running `sed -i 's|releasever=8.3|releasever=8|' /usr/share/convert2rhel/configs/centos-8-x86_64.cfg` before running convert2rhel.
There's a way to go without any workaround - if you don't need the convert2rhel package to be signed by Red Hat, you can already use the unsigned version 0.22 package attached to https://github.com/oamg/convert2rhel/releases/tag/v0.22.

**Comment by pixel-paul** [comment]
Thanks @bocekm, that has worked on my test system - conversion successful!

**Comment by bocekm** [comment]
The original issue is about a failure when using a RHEL ISO for the conversion, which is not supported for various reasons as I stated in https://github.com/oamg/convert2rhel/issues/277#issuecomment-843361034.

Then the other comments revolved around not being able to convert to RHEL 8.4. It is now officially possible with the version convert2rhel-0.22-1.el8.noarch available from today at https://ftp.redhat.com/redhat/convert2rhel/8/os/. All the steps to do that are described at https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/converting_from_an_rpm-based_linux_distribution_to_rhel/index.
