### ISSUE TITLE
RHEL 8.5 doesn't work

### ISSUE THREAD

**Issue by T5wxnxWgbJF6** [oamg/convert2rhel#366]
I tried convert from a centos 8.4 to a rhel 8.4. it looks like he now tries to update to rhel 8.5 (which was released yesterday) and fails with the following error:

`('[%s] %s - %s', '11/10/2021 10:53:00', 'DEBUG', "Calling command 'yum install -y --setopt=module_platform_id=platform:el8 /usr/share/convert2rhel/subscription-manager/subscription-manager-1.28.21-3.el8.x86_64.rpm /usr/share/convert2rhel/subs
cription-manager/subscription-manager-rhsm-certificates-1.28.21-3.el8.x86_64.rpm /usr/share/convert2rhel/subscription-manager/python3-subscription-manager-rhsm-1.28.21-3.el8.x86_64.rpm /usr/share/convert2rhel/subscription-manager/dnf-plugin-s
ubscription-manager-1.28.21-3.el8.x86_64.rpm /usr/share/convert2rhel/subscription-manager/python3-syspurpose-1.28.21-3.el8.x86_64.rpm'")
Failed loading plugin "spacewalk": No module named 'up2date_client'
Last metadata expiration check: 0:34:02 ago on Wed Nov 10 10:18:58 2021.
Error:
 Problem 1: conflicting requests
  - nothing provides python3-cloud-what = 1.28.21-3.el8 needed by subscription-manager-1.28.21-3.el8.x86_64
 Problem 2: conflicting requests
  - nothing provides python3-cloud-what = 1.28.21-3.el8 needed by python3-subscription-manager-rhsm-1.28.21-3.el8.x86_64
(try to add '--skip-broken' to skip uninstallable packages)
CRITICAL - Failed to install subscription-manager packages. See the above yum output for details.
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/convert2rhel/main.py", line 91, in main
    pre_ponr_conversion()
  File "/usr/lib/python3.6/site-packages/convert2rhel/main.py", line 182, in pre_ponr_conversion
    subscription.replace_subscription_manager()
  File "/usr/lib/python3.6/site-packages/convert2rhel/subscription.py", line 204, in replace_subscription_manager
    install_rhel_subscription_manager()
  File "/usr/lib/python3.6/site-packages/convert2rhel/subscription.py", line 246, in install_rhel_subscription_manager
    loggerinst.critical("Failed to install subscription-manager packages. See the above yum output for details.")
  File "/usr/lib/python3.6/site-packages/convert2rhel/logger.py", line 104, in _critical
    sys.exit(msg)
SystemExit: Failed to install subscription-manager packages. See the above yum output for details.
`

According to the documentation he should upgrade from centos 8.4 to rhel 8.4 and not the next higher minor.
Is there anything I can do so he stays on the same minor?

**Comment by Slapper** [comment]
Hello,

I am also experiencing the same issue . To overcome this one as @jordikroon  described  you have to install  the following packages  :
 
```
  yum install python3-requests
  rpm -ivh https://rpmfind.net/linux/centos/8-stream/BaseOS/x86_64/os/Packages/python3-cloud-what-1.28.21-3.el8.x86_64.rpm
```

**Comment by bocekm** [comment]
Sorry for the inconvenience. Another, one-line workaround is to manually download the `python3-cloud-what` package to a folder from which convert2rhel will pick it up and install during the conversion:

```
wget -P /usr/share/convert2rhel/subscription-manager/ -x https://cdn-ubi.redhat.com/content/public/ubi/dist/ubi8/8/x86_64/baseos/os/Packages/p/python3-cloud-what-1.28.21-3.el8.x86_64.rpm
```

**Comment by bocekm** [comment]
For reference - the bug has been filed in Bugzilla as well: https://bugzilla.redhat.com/show_bug.cgi?id=2022152

**Comment by T5wxnxWgbJF6** [comment]
thanks alot @bocekm !

**Comment by SvenVD** [comment]
For reference, you could also workaround this bug with

yum install subscription-manager ( from centos repos)
convert2rhel --username xxx--password xxx--pool xxx--keep-rhsm

**Comment by bocekm** [comment]
Both Oracle Linux and CentOS Linux 8.5 has been publicly released. I highly recommend updating your system to this new minor version as after doing so this issue will not appear anymore - no workaround is needed then.

Also, for the conversion process to be supported by Red Hat, one needs to follow the system preparation steps as documented at https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/converting_from_an_rpm-based_linux_distribution_to_rhel/index where one of the steps is to update the system to the latest minor version first.
