### ISSUE TITLE
/usr/bin/java alternatives lost

### ISSUE THREAD

**Issue by opoplawski** [oamg/convert2rhel#395]
The last two conversions of a centos IPA server ended up loosing the java alternatives symlinks.  Recreated by running the scriptlet from java-1.8.0-openjdk-headless.

**Comment by SpyTec** [comment]
Hi! Thanks for telling us how you fixed it. We have seen the issue before and it's in our backlog to look into :+1:

**Comment by bocekm** [comment]
For reference, the bug has been filed also here: https://bugzilla.redhat.com/show_bug.cgi?id=2032526.

**Comment by opoplawski** [comment]
Unfortunately that's a private bug so I can't see it.

**Comment by bocekm** [comment]
Sorry about that, I've just made it public.

**Comment by bocekm** [comment]
@opoplawski, we closed the related bugzilla. See comment https://bugzilla.redhat.com/show_bug.cgi?id=2032526#c5 for the reasoning. Feel free to reopen this issue or comment on the bugzilla if you find it incomplete.
