### ISSUE TITLE
Conversion from Rocky Linux 8.6 to RHEL 8.6 Fails

### ISSUE THREAD

**Issue by khanhibus** [oamg/convert2rhel#498]
Hi,

I am getting the following error when converting from Rocky Linux 8.6 to RHEL 8.6:

![image](https://user-images.githubusercontent.com/11794738/168909248-9604f212-ae1d-4f1d-8fda-ccdabae4e719.png)

Does the tool need to be updated for this scenario to be supported?

**Comment by bocekm** [comment]
Hi @khanhibus, the latest released version of convert2rhel 0.25 does not allow the Rocky 8 conversion yet. For that, you need to install a development version of convert2rhel from the Fedora Copr https://copr.fedorainfracloud.org/coprs/g/oamg/convert2rhel/. You can do that by:

```
# yum-config-manager --add-repo https://copr.fedorainfracloud.org/coprs/g/oamg/convert2rhel/repo/epel-8/group_oamg-convert2rhel-epel-8.repo
# yum install -y "convert2rhel*main*"  # a package built out of the main development branch
```

**Comment by khanhibus** [comment]
Hi @bocekm,

Thanks for your responses.

I tried the development version of convert2rhel and it worked for the most part. As I am using a local repo server to distribute RHEL 8 packages, I am only downloading the newest versions of packages. The convert2rhel command threw an error that it wanted to install **kernel-4.18.0-348.12.2.el8_5.x86_64**, which is older than what is currently available from my local repo (**kernel-4.18.0-372.9.1.el8.x86_64**). 

I had to download the older kernel package on my repo server, at which point the convert2rhel task completed successfully. Something to note is that after the first conversion attempt failed, it deleted the /etc/system-release file. Running the convert2rhel command again failed because that file was missing. Luckily this was VM that I snapshotted prior to the conversion attempt, but for others that have a similar use case to mine, be mindful that if this process fails on your first attempt, especially if running on bare metal with no backups.

**Comment by bocekm** [comment]
> The convert2rhel command threw an error that it wanted to install kernel-4.18.0-348.12.2.el8_5.x86_64, which is older than what is currently available from my local repo (kernel-4.18.0-372.9.1.el8.x86_64).

Don't you happen to have a log file containing this error? I wonder what was the reason for it. Since you use a local repo server I expect you used the `--disable-rhsm` and `--enablerepo` options. And in that case when installing the RHEL kernel, a yum command like the following is called so it should install whatever kernel is available in your local repo.
```
# yum install -y --disablerepo="*" --releasever=8.6 --setopt=module_platform_id=platform:el8 --enablerepo=<your_local_server_repo> kernel
```

---

Regarding the deleted `/etc/system-release` file. Unfortunately the error you've bumped into happened after the "point of no return" about which the tool warns the user by printing `WARNING - The tool allows rollback of any action until this point`. Indeed, a full system backup is strongly recommended before performing the conversion.

**Comment by khanhibus** [comment]
@bocekm, I was using the following command to invoke the upgrade:

`convert2rhel --no-rhsm --enablerepo=rhel-8-for-x86_64-baseos-rpms --enablerepo=rhel-8-for-x86_64-appstream-rpms --restart -y`

I have not tried to convert any other Rocky Linux systems since I opened this issue but will be sure to upload any new logs should I convert another system in the future and encounter the same error.

**Comment by khanhibus** [comment]
@bocekm, I did another convert2rhel conversion from Rocky Linux 8.6 to RHEL 8.6 and encountered the same issue with the conversion process not wanting to install the latest kernel. Here are the relevant log lines, as requested:
```
[06/01/2022 10:03:22] TASK - [Convert: Prepare kernel] ******************************************
Installing RHEL kernel ...
[06/01/2022 10:03:22] FILE - Calling command 'yum install -y --disablerepo=* --releasever=8.6 --setopt=module_platform_id=platform:el8 --enablerepo=rhel-8-for-x86_64-baseos-rpms kernel'
Failed loading plugin "spacewalk": No module named 'up2date_client'
Last metadata expiration check: 0:02:36 ago on Wed Jun  1 10:00:47 2022.
Package kernel-4.18.0-348.20.1.el8_5.x86_64 is already installed.
Package kernel-4.18.0-348.23.1.el8_5.x86_64 is already installed.
Package kernel-4.18.0-372.9.1.el8.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!

Conflict of kernels: One of the installed kernels has the same version as the latest RHEL kernel.
[06/01/2022 10:03:23] FILE - Calling command 'yum list -y --disablerepo=* --releasever=8.6 --setopt=module_platform_id=platform:el8 --enablerepo=rhel-8-for-x86_64-baseos-rpms --showduplicates kernel'
[06/01/2022 10:03:24] FILE - Calling command 'yum install -y --disablerepo=* --releasever=8.6 --setopt=module_platform_id=platform:el8 --enablerepo=rhel-8-for-x86_64-baseos-rpms kernel-4.18.0-348.12.2.el8_5'
Failed loading plugin "spacewalk": No module named 'up2date_client'
Last metadata expiration check: 0:02:38 ago on Wed Jun  1 10:00:47 2022.
Dependencies resolved.
================================================================================
 Package       Arch   Version               Repository                     Size
================================================================================
Installing:
 kernel        x86_64 4.18.0-348.12.2.el8_5 rhel-8-for-x86_64-baseos-rpms 7.0 M
 kernel-core   x86_64 4.18.0-348.12.2.el8_5 rhel-8-for-x86_64-baseos-rpms  38 M
 kernel-modules
               x86_64 4.18.0-348.12.2.el8_5 rhel-8-for-x86_64-baseos-rpms  30 M
Removing:
 kernel        x86_64 4.18.0-348.20.1.el8_5 @internal-baseos                0  
 kernel-core   x86_64 4.18.0-348.20.1.el8_5 @internal-baseos               68 M
 kernel-modules
               x86_64 4.18.0-348.20.1.el8_5 @internal-baseos               22 M

Transaction Summary
================================================================================
Install  3 Packages
Remove   3 Packages

Total download size: 74 M
Downloading Packages:
(1/3): kernel-4.18.0-348.12.2.el8_5.x86_64.rpm  1.3 MB/s | 7.0 MB     00:05    
(2/3): kernel-modules-4.18.0-348.12.2.el8_5.x86 5.5 MB/s |  30 MB     00:05    
(3/3): kernel-core-4.18.0-348.12.2.el8_5.x86_64 6.7 MB/s |  38 MB     00:05    
--------------------------------------------------------------------------------
Total                                            13 MB/s |  74 MB     00:05     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                        1/1 
  Installing       : kernel-core-4.18.0-348.12.2.el8_5.x86_64               1/6 
  Running scriptlet: kernel-core-4.18.0-348.12.2.el8_5.x86_64               1/6 
  Installing       : kernel-modules-4.18.0-348.12.2.el8_5.x86_64            2/6 
  Running scriptlet: kernel-modules-4.18.0-348.12.2.el8_5.x86_64            2/6 
  Installing       : kernel-4.18.0-348.12.2.el8_5.x86_64                    3/6 
  Erasing          : kernel-4.18.0-348.20.1.el8_5.x86_64                    4/6 
  Running scriptlet: kernel-4.18.0-348.20.1.el8_5.x86_64                    4/6 
  Erasing          : kernel-modules-4.18.0-348.20.1.el8_5.x86_64            5/6 
  Running scriptlet: kernel-modules-4.18.0-348.20.1.el8_5.x86_64            5/6 
  Running scriptlet: kernel-core-4.18.0-348.20.1.el8_5.x86_64               6/6 
sed: can't read /etc/system-release: No such file or directory
sed: can't read /etc/system-release: No such file or directory

  Erasing          : kernel-core-4.18.0-348.20.1.el8_5.x86_64               6/6 
  Running scriptlet: kernel-core-4.18.0-348.20.1.el8_5.x86_64               6/6 
  Running scriptlet: kernel-core-4.18.0-348.12.2.el8_5.x86_64               6/6 
sed: can't read /etc/system-release: No such file or directory
sed: can't read /etc/system-release: No such file or directory

  Running scriptlet: kernel-core-4.18.0-348.20.1.el8_5.x86_64               6/6 
  Verifying        : kernel-4.18.0-348.12.2.el8_5.x86_64                    1/6 
  Verifying        : kernel-modules-4.18.0-348.12.2.el8_5.x86_64            2/6 
  Verifying        : kernel-core-4.18.0-348.12.2.el8_5.x86_64               3/6 
  Verifying        : kernel-4.18.0-348.20.1.el8_5.x86_64                    4/6 
  Verifying        : kernel-core-4.18.0-348.20.1.el8_5.x86_64               5/6 
  Verifying        : kernel-modules-4.18.0-348.20.1.el8_5.x86_64            6/6 

Installed:
  kernel-4.18.0-348.12.2.el8_5.x86_64                                           
  kernel-core-4.18.0-348.12.2.el8_5.x86_64                                      
  kernel-modules-4.18.0-348.12.2.el8_5.x86_64                                   
Removed:
  kernel-4.18.0-348.20.1.el8_5.x86_64                                           
  kernel-core-4.18.0-348.20.1.el8_5.x86_64                                      
  kernel-modules-4.18.0-348.20.1.el8_5.x86_64                                   
```

I believe the relevant log line is: `Conflict of kernels: One of the installed kernels has the same version as the latest RHEL kernel.`

The install did not fail as I already have the `kernel-*-4.18.0-348.12.2.el8_5.x86_64`  RPMs in my local repo, but hopefully this helps in debugging the issue.

**Comment by bocekm** [comment]
@khanhibus, the conversion of Rocky Linux 8.6/8.8 does not fail anymore with the current state of https://github.com/oamg/convert2rhel/pull/883.

@jochapma will create a new issue to track the problem with having old kernel version installed after the conversion.
