### ISSUE TITLE
Convert failed

### ISSUE THREAD

**Issue by rajatjpatel** [oamg/convert2rhel#738]
Below issues I am facing 

[02/16/2023 05:48:27] TASK - [Prepare: Gather system information] *******************************
CRITICAL - Couldn't get system version from /etc/system-release
Writing breadcrumbs to '/etc/migration-results'.
Writing RHSM custom facts to '/etc/rhsm/facts/convert2rhel.facts'.
No changes were made to the system.

[root@pg2 ~]# cat /etc/os-release 
NAME="CentOS Stream"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Stream 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"

[root@pg2 ~]# uname -a
Linux pg2 4.18.0-448.el8.x86_64 #1 SMP Wed Jan 18 15:02:46 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by rajatjpatel** [comment]
[root@pg2 ~]# grep . /etc/*-release
/etc/centos-release:CentOS Stream release 8
/etc/os-release:NAME="CentOS Stream"
/etc/os-release:VERSION="8"
/etc/os-release:ID="centos"
/etc/os-release:ID_LIKE="rhel fedora"
/etc/os-release:VERSION_ID="8"
/etc/os-release:PLATFORM_ID="platform:el8"
/etc/os-release:PRETTY_NAME="CentOS Stream 8"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:centos:centos:8"
/etc/os-release:HOME_URL="https://centos.org/"
/etc/os-release:BUG_REPORT_URL="https://bugzilla.redhat.com/"
/etc/os-release:REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 8"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"
/etc/redhat-release:CentOS Stream release 8
/etc/system-release:CentOS Stream release 8

**Comment by SpyTec** [comment]
Hi. I notice you're trying to Convert a CentOS Stream release. That is currently not possible as we only support CentOS Linux conversions
