### ISSUE TITLE
convert2rhel migration error

### ISSUE THREAD

**Issue by vishnupjk** [oamg/convert2rhel#824]
I am trying to migrate from centos 7.9 to rhel 7.9 using convert2rhel utility [custom repo].

I have performed 'yum update' and installed the gpg keys and convert2rhel utility as well.

while migration, I am getting the error message "no packages containing kernel modules available in the enabled repositories"

kindly help to fix this issue.

**Comment by r0x0d** [comment]
Hi, @vishnupjk! Thanks for your first issue! 

Could you please share with us the log for this conversion? It will help us debug and understand what could be wrong with it.

**Comment by abadger** [comment]
@vishnupjk I have a potential fix for this finished in #818 if you would care to try it out to see if that is indeed your problem.

**Comment by bocekm** [comment]
#818 merged, closing the issue as fixed. @vishnupjk, if you still facing this or similar problem, please reopen the issue.
