### ISSUE TITLE
Error Message if LIST_THIRD_PARTY_PACKAGES

### ISSUE THREAD

**Issue by zionnoizy** [oamg/convert2rhel#944]
I install convert2rhel yesturday, and have a centOS7 and I want to do the upgrade. After I run "convert2rhel". I see this message

![image](https://github.com/oamg/convert2rhel/assets/54279382/73aaa58f-7cf7-49f2-b3ef-9d0f6b9ead5d)

so I am not sure where is the nmap comes from and I don't know if I exclude it will run correctly? Why it has this error and how to resolve it? Thank you in advanced.

**Comment by r0x0d** [comment]
Hi, @zionnoizy! 

The strange thing to me is that the epoch is missing. Not sure what happened there, but it is definitely a bug. 

Could you run a few commands before, just to check the output for me? Namely: 
```bash
rpm -qi nmap
```

```bash
rpm -qf C2R %{PACKAGER}&%{VENDOR}&%{NAME}-%|EPOCH?{%{EPOCH}}:{0}|:%{VERSION}-%{RELEASE}.%{ARCH}&%|DSAHEADER?{%{DSAHEADER:pgpsig}}:{%|RSAHEADER?{%{RSAHEADER:pgpsig}}:{%|SIGGPG?{%{SIGGPG:pgpsig}}:{%|SIGPGP?{%{SIGPGP:pgpsig}}:{(none)}|}|}|}|\n -q npm
```


convert2rhel has a configuration file that lets you add some packages to the exclude_list, and it will take care of removing it for you during the conversion (if something goes wrong, convert2rhel will install the package back). Please, take a look at: https://github.com/oamg/convert2rhel/blob/main/convert2rhel/data/7/x86_64/configs/centos-7-x86_64.cfg#L10

**Comment by bocekm** [comment]
This has been fixed by https://github.com/oamg/convert2rhel/pull/984.
